/*
 * Copyright (C) 2026 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/css/names.py"!
 * Do not change this file!
 */


#ifndef LXB_CSS_UNIT_RES_H
#define LXB_CSS_UNIT_RES_H

#include "lexbor/core/shs.h"
#include "lexbor/css/unit/const.h"


static const lxb_css_data_t lxb_css_unit_data[LXB_CSS_UNIT__LAST_ENTRY] = 
{
    {
        .name = (lxb_char_t *) "#undef",
        .length = 6,
        .unique = LXB_CSS_UNIT__UNDEF
    },
    {
        .name = (lxb_char_t *) "Q",
        .length = 1,
        .unique = LXB_CSS_UNIT_Q
    },
    {
        .name = (lxb_char_t *) "cm",
        .length = 2,
        .unique = LXB_CSS_UNIT_CM
    },
    {
        .name = (lxb_char_t *) "in",
        .length = 2,
        .unique = LXB_CSS_UNIT_IN
    },
    {
        .name = (lxb_char_t *) "mm",
        .length = 2,
        .unique = LXB_CSS_UNIT_MM
    },
    {
        .name = (lxb_char_t *) "pc",
        .length = 2,
        .unique = LXB_CSS_UNIT_PC
    },
    {
        .name = (lxb_char_t *) "pt",
        .length = 2,
        .unique = LXB_CSS_UNIT_PT
    },
    {
        .name = (lxb_char_t *) "px",
        .length = 2,
        .unique = LXB_CSS_UNIT_PX
    },
    {
        .name = (lxb_char_t *) "cap",
        .length = 3,
        .unique = LXB_CSS_UNIT_CAP
    },
    {
        .name = (lxb_char_t *) "ch",
        .length = 2,
        .unique = LXB_CSS_UNIT_CH
    },
    {
        .name = (lxb_char_t *) "em",
        .length = 2,
        .unique = LXB_CSS_UNIT_EM
    },
    {
        .name = (lxb_char_t *) "ex",
        .length = 2,
        .unique = LXB_CSS_UNIT_EX
    },
    {
        .name = (lxb_char_t *) "ic",
        .length = 2,
        .unique = LXB_CSS_UNIT_IC
    },
    {
        .name = (lxb_char_t *) "lh",
        .length = 2,
        .unique = LXB_CSS_UNIT_LH
    },
    {
        .name = (lxb_char_t *) "rem",
        .length = 3,
        .unique = LXB_CSS_UNIT_REM
    },
    {
        .name = (lxb_char_t *) "rlh",
        .length = 3,
        .unique = LXB_CSS_UNIT_RLH
    },
    {
        .name = (lxb_char_t *) "vb",
        .length = 2,
        .unique = LXB_CSS_UNIT_VB
    },
    {
        .name = (lxb_char_t *) "vh",
        .length = 2,
        .unique = LXB_CSS_UNIT_VH
    },
    {
        .name = (lxb_char_t *) "vi",
        .length = 2,
        .unique = LXB_CSS_UNIT_VI
    },
    {
        .name = (lxb_char_t *) "vmax",
        .length = 4,
        .unique = LXB_CSS_UNIT_VMAX
    },
    {
        .name = (lxb_char_t *) "vmin",
        .length = 4,
        .unique = LXB_CSS_UNIT_VMIN
    },
    {
        .name = (lxb_char_t *) "vw",
        .length = 2,
        .unique = LXB_CSS_UNIT_VW
    },
    {
        .name = (lxb_char_t *) "deg",
        .length = 3,
        .unique = LXB_CSS_UNIT_DEG
    },
    {
        .name = (lxb_char_t *) "grad",
        .length = 4,
        .unique = LXB_CSS_UNIT_GRAD
    },
    {
        .name = (lxb_char_t *) "rad",
        .length = 3,
        .unique = LXB_CSS_UNIT_RAD
    },
    {
        .name = (lxb_char_t *) "turn",
        .length = 4,
        .unique = LXB_CSS_UNIT_TURN
    },
    {
        .name = (lxb_char_t *) "Hz",
        .length = 2,
        .unique = LXB_CSS_UNIT_HZ
    },
    {
        .name = (lxb_char_t *) "kHz",
        .length = 3,
        .unique = LXB_CSS_UNIT_KHZ
    },
    {
        .name = (lxb_char_t *) "dpcm",
        .length = 4,
        .unique = LXB_CSS_UNIT_DPCM
    },
    {
        .name = (lxb_char_t *) "dpi",
        .length = 3,
        .unique = LXB_CSS_UNIT_DPI
    },
    {
        .name = (lxb_char_t *) "dppx",
        .length = 4,
        .unique = LXB_CSS_UNIT_DPPX
    },
    {
        .name = (lxb_char_t *) "x",
        .length = 1,
        .unique = LXB_CSS_UNIT_X
    },
    {
        .name = (lxb_char_t *) "ms",
        .length = 2,
        .unique = LXB_CSS_UNIT_MS
    },
    {
        .name = (lxb_char_t *) "s",
        .length = 1,
        .unique = LXB_CSS_UNIT_S
    }
};

static const lexbor_shs_entry_t lxb_css_unit_absolute_relative_shs[84] = 
{
    {NULL, NULL, 83, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"rem", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_REM], 3, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"vmax", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_VMAX], 4, 0}, 
    {"pc", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_PC], 2, 0}, 
    {"lh", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_LH], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {"rlh", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_RLH], 3, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"cm", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_CM], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"q", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_Q], 1, 0}, 
    {"ic", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_IC], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {"vw", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_VW], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"pt", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_PT], 2, 0}, 
    {"vb", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_VB], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"ex", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_EX], 2, 0}, 
    {"in", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_IN], 2, 0}, 
    {"cap", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_CAP], 3, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"em", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_EM], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {"vmin", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_VMIN], 4, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"vi", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_VI], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"mm", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_MM], 2, 0}, 
    {"ch", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_CH], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"px", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_PX], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"vh", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_VH], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}
};

static const lexbor_shs_entry_t lxb_css_unit_absolute_shs[30] = 
{
    {NULL, NULL, 29, 0}, 
    {NULL, NULL, 0, 0}, 
    {"in", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_IN], 2, 0}, 
    {"pt", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_PT], 2, 0}, 
    {"q", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_Q], 1, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"mm", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_MM], 2, 0}, 
    {"px", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_PX], 2, 0}, 
    {"cm", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_CM], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"pc", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_PC], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}
};

static const lexbor_shs_entry_t lxb_css_unit_relative_shs[64] = 
{
    {NULL, NULL, 63, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"ic", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_IC], 2, 0}, 
    {"cap", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_CAP], 3, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"rem", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_REM], 3, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"em", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_EM], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"ch", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_CH], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"ex", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_EX], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"vb", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_VB], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"vh", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_VH], 2, 0}, 
    {"vi", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_VI], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"rlh", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_RLH], 3, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"vmin", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_VMIN], 4, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"lh", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_LH], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {"vw", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_VW], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"vmax", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_VMAX], 4, 0}, 
    {NULL, NULL, 0, 0}
};

static const lexbor_shs_entry_t lxb_css_unit_angle_shs[7] = 
{
    {NULL, NULL, 6, 0}, 
    {"turn", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_TURN], 4, 0}, 
    {"deg", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_DEG], 3, 0}, 
    {"grad", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_GRAD], 4, 0}, 
    {"rad", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_RAD], 3, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}
};

static const lexbor_shs_entry_t lxb_css_unit_frequency_shs[6] = 
{
    {NULL, NULL, 5, 0}, 
    {NULL, NULL, 0, 0}, 
    {"khz", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_KHZ], 3, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"hz", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_HZ], 2, 0}
};

static const lexbor_shs_entry_t lxb_css_unit_resolution_shs[7] = 
{
    {NULL, NULL, 6, 0}, 
    {NULL, NULL, 0, 0}, 
    {"x", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_X], 1, 0}, 
    {"dpcm", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_DPCM], 4, 0}, 
    {"dpi", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_DPI], 3, 0}, 
    {"dppx", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_DPPX], 4, 0}, 
    {NULL, NULL, 0, 0}
};

static const lexbor_shs_entry_t lxb_css_unit_duration_shs[6] = 
{
    {NULL, NULL, 5, 0}, 
    {NULL, NULL, 0, 0}, 
    {"s", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_S], 1, 0}, 
    {"ms", (void *) &lxb_css_unit_data[LXB_CSS_UNIT_MS], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}
};




#endif /* LXB_CSS_UNIT_RES_H */
