/*
 * Copyright (C) 2026 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/css/names.py"!
 * Do not change this file!
 */


#ifndef LXB_CSS_VALUE_RES_H
#define LXB_CSS_VALUE_RES_H

#include "lexbor/core/shs.h"
#include "lexbor/css/value/const.h"

static const lxb_css_data_t lxb_css_value_data[LXB_CSS_VALUE__LAST_ENTRY] = 
{
    {
        .name = (lxb_char_t *) "_undef",
        .length = 6,
        .unique = LXB_CSS_VALUE__UNDEF
    },
    {
        .name = (lxb_char_t *) "initial",
        .length = 7,
        .unique = LXB_CSS_VALUE_INITIAL
    },
    {
        .name = (lxb_char_t *) "inherit",
        .length = 7,
        .unique = LXB_CSS_VALUE_INHERIT
    },
    {
        .name = (lxb_char_t *) "unset",
        .length = 5,
        .unique = LXB_CSS_VALUE_UNSET
    },
    {
        .name = (lxb_char_t *) "revert",
        .length = 6,
        .unique = LXB_CSS_VALUE_REVERT
    },
    {
        .name = (lxb_char_t *) "flex-start",
        .length = 10,
        .unique = LXB_CSS_VALUE_FLEX_START
    },
    {
        .name = (lxb_char_t *) "flex-end",
        .length = 8,
        .unique = LXB_CSS_VALUE_FLEX_END
    },
    {
        .name = (lxb_char_t *) "center",
        .length = 6,
        .unique = LXB_CSS_VALUE_CENTER
    },
    {
        .name = (lxb_char_t *) "space-between",
        .length = 13,
        .unique = LXB_CSS_VALUE_SPACE_BETWEEN
    },
    {
        .name = (lxb_char_t *) "space-around",
        .length = 12,
        .unique = LXB_CSS_VALUE_SPACE_AROUND
    },
    {
        .name = (lxb_char_t *) "stretch",
        .length = 7,
        .unique = LXB_CSS_VALUE_STRETCH
    },
    {
        .name = (lxb_char_t *) "baseline",
        .length = 8,
        .unique = LXB_CSS_VALUE_BASELINE
    },
    {
        .name = (lxb_char_t *) "auto",
        .length = 4,
        .unique = LXB_CSS_VALUE_AUTO
    },
    {
        .name = (lxb_char_t *) "text-bottom",
        .length = 11,
        .unique = LXB_CSS_VALUE_TEXT_BOTTOM
    },
    {
        .name = (lxb_char_t *) "alphabetic",
        .length = 10,
        .unique = LXB_CSS_VALUE_ALPHABETIC
    },
    {
        .name = (lxb_char_t *) "ideographic",
        .length = 11,
        .unique = LXB_CSS_VALUE_IDEOGRAPHIC
    },
    {
        .name = (lxb_char_t *) "middle",
        .length = 6,
        .unique = LXB_CSS_VALUE_MIDDLE
    },
    {
        .name = (lxb_char_t *) "central",
        .length = 7,
        .unique = LXB_CSS_VALUE_CENTRAL
    },
    {
        .name = (lxb_char_t *) "mathematical",
        .length = 12,
        .unique = LXB_CSS_VALUE_MATHEMATICAL
    },
    {
        .name = (lxb_char_t *) "text-top",
        .length = 8,
        .unique = LXB_CSS_VALUE_TEXT_TOP
    },
    {
        .name = (lxb_char_t *) "_length",
        .length = 7,
        .unique = LXB_CSS_VALUE__LENGTH
    },
    {
        .name = (lxb_char_t *) "_percentage",
        .length = 11,
        .unique = LXB_CSS_VALUE__PERCENTAGE
    },
    {
        .name = (lxb_char_t *) "sub",
        .length = 3,
        .unique = LXB_CSS_VALUE_SUB
    },
    {
        .name = (lxb_char_t *) "super",
        .length = 5,
        .unique = LXB_CSS_VALUE_SUPER
    },
    {
        .name = (lxb_char_t *) "top",
        .length = 3,
        .unique = LXB_CSS_VALUE_TOP
    },
    {
        .name = (lxb_char_t *) "bottom",
        .length = 6,
        .unique = LXB_CSS_VALUE_BOTTOM
    },
    {
        .name = (lxb_char_t *) "first",
        .length = 5,
        .unique = LXB_CSS_VALUE_FIRST
    },
    {
        .name = (lxb_char_t *) "last",
        .length = 4,
        .unique = LXB_CSS_VALUE_LAST
    },
    {
        .name = (lxb_char_t *) "thin",
        .length = 4,
        .unique = LXB_CSS_VALUE_THIN
    },
    {
        .name = (lxb_char_t *) "medium",
        .length = 6,
        .unique = LXB_CSS_VALUE_MEDIUM
    },
    {
        .name = (lxb_char_t *) "thick",
        .length = 5,
        .unique = LXB_CSS_VALUE_THICK
    },
    {
        .name = (lxb_char_t *) "none",
        .length = 4,
        .unique = LXB_CSS_VALUE_NONE
    },
    {
        .name = (lxb_char_t *) "hidden",
        .length = 6,
        .unique = LXB_CSS_VALUE_HIDDEN
    },
    {
        .name = (lxb_char_t *) "dotted",
        .length = 6,
        .unique = LXB_CSS_VALUE_DOTTED
    },
    {
        .name = (lxb_char_t *) "dashed",
        .length = 6,
        .unique = LXB_CSS_VALUE_DASHED
    },
    {
        .name = (lxb_char_t *) "solid",
        .length = 5,
        .unique = LXB_CSS_VALUE_SOLID
    },
    {
        .name = (lxb_char_t *) "double",
        .length = 6,
        .unique = LXB_CSS_VALUE_DOUBLE
    },
    {
        .name = (lxb_char_t *) "groove",
        .length = 6,
        .unique = LXB_CSS_VALUE_GROOVE
    },
    {
        .name = (lxb_char_t *) "ridge",
        .length = 5,
        .unique = LXB_CSS_VALUE_RIDGE
    },
    {
        .name = (lxb_char_t *) "inset",
        .length = 5,
        .unique = LXB_CSS_VALUE_INSET
    },
    {
        .name = (lxb_char_t *) "outset",
        .length = 6,
        .unique = LXB_CSS_VALUE_OUTSET
    },
    {
        .name = (lxb_char_t *) "content-box",
        .length = 11,
        .unique = LXB_CSS_VALUE_CONTENT_BOX
    },
    {
        .name = (lxb_char_t *) "border-box",
        .length = 10,
        .unique = LXB_CSS_VALUE_BORDER_BOX
    },
    {
        .name = (lxb_char_t *) "inline-start",
        .length = 12,
        .unique = LXB_CSS_VALUE_INLINE_START
    },
    {
        .name = (lxb_char_t *) "inline-end",
        .length = 10,
        .unique = LXB_CSS_VALUE_INLINE_END
    },
    {
        .name = (lxb_char_t *) "block-start",
        .length = 11,
        .unique = LXB_CSS_VALUE_BLOCK_START
    },
    {
        .name = (lxb_char_t *) "block-end",
        .length = 9,
        .unique = LXB_CSS_VALUE_BLOCK_END
    },
    {
        .name = (lxb_char_t *) "left",
        .length = 4,
        .unique = LXB_CSS_VALUE_LEFT
    },
    {
        .name = (lxb_char_t *) "right",
        .length = 5,
        .unique = LXB_CSS_VALUE_RIGHT
    },
    {
        .name = (lxb_char_t *) "currentcolor",
        .length = 12,
        .unique = LXB_CSS_VALUE_CURRENTCOLOR
    },
    {
        .name = (lxb_char_t *) "transparent",
        .length = 11,
        .unique = LXB_CSS_VALUE_TRANSPARENT
    },
    {
        .name = (lxb_char_t *) "hex",
        .length = 3,
        .unique = LXB_CSS_VALUE_HEX
    },
    {
        .name = (lxb_char_t *) "aliceblue",
        .length = 9,
        .unique = LXB_CSS_VALUE_ALICEBLUE
    },
    {
        .name = (lxb_char_t *) "antiquewhite",
        .length = 12,
        .unique = LXB_CSS_VALUE_ANTIQUEWHITE
    },
    {
        .name = (lxb_char_t *) "aqua",
        .length = 4,
        .unique = LXB_CSS_VALUE_AQUA
    },
    {
        .name = (lxb_char_t *) "aquamarine",
        .length = 10,
        .unique = LXB_CSS_VALUE_AQUAMARINE
    },
    {
        .name = (lxb_char_t *) "azure",
        .length = 5,
        .unique = LXB_CSS_VALUE_AZURE
    },
    {
        .name = (lxb_char_t *) "beige",
        .length = 5,
        .unique = LXB_CSS_VALUE_BEIGE
    },
    {
        .name = (lxb_char_t *) "bisque",
        .length = 6,
        .unique = LXB_CSS_VALUE_BISQUE
    },
    {
        .name = (lxb_char_t *) "black",
        .length = 5,
        .unique = LXB_CSS_VALUE_BLACK
    },
    {
        .name = (lxb_char_t *) "blanchedalmond",
        .length = 14,
        .unique = LXB_CSS_VALUE_BLANCHEDALMOND
    },
    {
        .name = (lxb_char_t *) "blue",
        .length = 4,
        .unique = LXB_CSS_VALUE_BLUE
    },
    {
        .name = (lxb_char_t *) "blueviolet",
        .length = 10,
        .unique = LXB_CSS_VALUE_BLUEVIOLET
    },
    {
        .name = (lxb_char_t *) "brown",
        .length = 5,
        .unique = LXB_CSS_VALUE_BROWN
    },
    {
        .name = (lxb_char_t *) "burlywood",
        .length = 9,
        .unique = LXB_CSS_VALUE_BURLYWOOD
    },
    {
        .name = (lxb_char_t *) "cadetblue",
        .length = 9,
        .unique = LXB_CSS_VALUE_CADETBLUE
    },
    {
        .name = (lxb_char_t *) "chartreuse",
        .length = 10,
        .unique = LXB_CSS_VALUE_CHARTREUSE
    },
    {
        .name = (lxb_char_t *) "chocolate",
        .length = 9,
        .unique = LXB_CSS_VALUE_CHOCOLATE
    },
    {
        .name = (lxb_char_t *) "coral",
        .length = 5,
        .unique = LXB_CSS_VALUE_CORAL
    },
    {
        .name = (lxb_char_t *) "cornflowerblue",
        .length = 14,
        .unique = LXB_CSS_VALUE_CORNFLOWERBLUE
    },
    {
        .name = (lxb_char_t *) "cornsilk",
        .length = 8,
        .unique = LXB_CSS_VALUE_CORNSILK
    },
    {
        .name = (lxb_char_t *) "crimson",
        .length = 7,
        .unique = LXB_CSS_VALUE_CRIMSON
    },
    {
        .name = (lxb_char_t *) "cyan",
        .length = 4,
        .unique = LXB_CSS_VALUE_CYAN
    },
    {
        .name = (lxb_char_t *) "darkblue",
        .length = 8,
        .unique = LXB_CSS_VALUE_DARKBLUE
    },
    {
        .name = (lxb_char_t *) "darkcyan",
        .length = 8,
        .unique = LXB_CSS_VALUE_DARKCYAN
    },
    {
        .name = (lxb_char_t *) "darkgoldenrod",
        .length = 13,
        .unique = LXB_CSS_VALUE_DARKGOLDENROD
    },
    {
        .name = (lxb_char_t *) "darkgray",
        .length = 8,
        .unique = LXB_CSS_VALUE_DARKGRAY
    },
    {
        .name = (lxb_char_t *) "darkgreen",
        .length = 9,
        .unique = LXB_CSS_VALUE_DARKGREEN
    },
    {
        .name = (lxb_char_t *) "darkgrey",
        .length = 8,
        .unique = LXB_CSS_VALUE_DARKGREY
    },
    {
        .name = (lxb_char_t *) "darkkhaki",
        .length = 9,
        .unique = LXB_CSS_VALUE_DARKKHAKI
    },
    {
        .name = (lxb_char_t *) "darkmagenta",
        .length = 11,
        .unique = LXB_CSS_VALUE_DARKMAGENTA
    },
    {
        .name = (lxb_char_t *) "darkolivegreen",
        .length = 14,
        .unique = LXB_CSS_VALUE_DARKOLIVEGREEN
    },
    {
        .name = (lxb_char_t *) "darkorange",
        .length = 10,
        .unique = LXB_CSS_VALUE_DARKORANGE
    },
    {
        .name = (lxb_char_t *) "darkorchid",
        .length = 10,
        .unique = LXB_CSS_VALUE_DARKORCHID
    },
    {
        .name = (lxb_char_t *) "darkred",
        .length = 7,
        .unique = LXB_CSS_VALUE_DARKRED
    },
    {
        .name = (lxb_char_t *) "darksalmon",
        .length = 10,
        .unique = LXB_CSS_VALUE_DARKSALMON
    },
    {
        .name = (lxb_char_t *) "darkseagreen",
        .length = 12,
        .unique = LXB_CSS_VALUE_DARKSEAGREEN
    },
    {
        .name = (lxb_char_t *) "darkslateblue",
        .length = 13,
        .unique = LXB_CSS_VALUE_DARKSLATEBLUE
    },
    {
        .name = (lxb_char_t *) "darkslategray",
        .length = 13,
        .unique = LXB_CSS_VALUE_DARKSLATEGRAY
    },
    {
        .name = (lxb_char_t *) "darkslategrey",
        .length = 13,
        .unique = LXB_CSS_VALUE_DARKSLATEGREY
    },
    {
        .name = (lxb_char_t *) "darkturquoise",
        .length = 13,
        .unique = LXB_CSS_VALUE_DARKTURQUOISE
    },
    {
        .name = (lxb_char_t *) "darkviolet",
        .length = 10,
        .unique = LXB_CSS_VALUE_DARKVIOLET
    },
    {
        .name = (lxb_char_t *) "deeppink",
        .length = 8,
        .unique = LXB_CSS_VALUE_DEEPPINK
    },
    {
        .name = (lxb_char_t *) "deepskyblue",
        .length = 11,
        .unique = LXB_CSS_VALUE_DEEPSKYBLUE
    },
    {
        .name = (lxb_char_t *) "dimgray",
        .length = 7,
        .unique = LXB_CSS_VALUE_DIMGRAY
    },
    {
        .name = (lxb_char_t *) "dimgrey",
        .length = 7,
        .unique = LXB_CSS_VALUE_DIMGREY
    },
    {
        .name = (lxb_char_t *) "dodgerblue",
        .length = 10,
        .unique = LXB_CSS_VALUE_DODGERBLUE
    },
    {
        .name = (lxb_char_t *) "firebrick",
        .length = 9,
        .unique = LXB_CSS_VALUE_FIREBRICK
    },
    {
        .name = (lxb_char_t *) "floralwhite",
        .length = 11,
        .unique = LXB_CSS_VALUE_FLORALWHITE
    },
    {
        .name = (lxb_char_t *) "forestgreen",
        .length = 11,
        .unique = LXB_CSS_VALUE_FORESTGREEN
    },
    {
        .name = (lxb_char_t *) "fuchsia",
        .length = 7,
        .unique = LXB_CSS_VALUE_FUCHSIA
    },
    {
        .name = (lxb_char_t *) "gainsboro",
        .length = 9,
        .unique = LXB_CSS_VALUE_GAINSBORO
    },
    {
        .name = (lxb_char_t *) "ghostwhite",
        .length = 10,
        .unique = LXB_CSS_VALUE_GHOSTWHITE
    },
    {
        .name = (lxb_char_t *) "gold",
        .length = 4,
        .unique = LXB_CSS_VALUE_GOLD
    },
    {
        .name = (lxb_char_t *) "goldenrod",
        .length = 9,
        .unique = LXB_CSS_VALUE_GOLDENROD
    },
    {
        .name = (lxb_char_t *) "gray",
        .length = 4,
        .unique = LXB_CSS_VALUE_GRAY
    },
    {
        .name = (lxb_char_t *) "green",
        .length = 5,
        .unique = LXB_CSS_VALUE_GREEN
    },
    {
        .name = (lxb_char_t *) "greenyellow",
        .length = 11,
        .unique = LXB_CSS_VALUE_GREENYELLOW
    },
    {
        .name = (lxb_char_t *) "grey",
        .length = 4,
        .unique = LXB_CSS_VALUE_GREY
    },
    {
        .name = (lxb_char_t *) "honeydew",
        .length = 8,
        .unique = LXB_CSS_VALUE_HONEYDEW
    },
    {
        .name = (lxb_char_t *) "hotpink",
        .length = 7,
        .unique = LXB_CSS_VALUE_HOTPINK
    },
    {
        .name = (lxb_char_t *) "indianred",
        .length = 9,
        .unique = LXB_CSS_VALUE_INDIANRED
    },
    {
        .name = (lxb_char_t *) "indigo",
        .length = 6,
        .unique = LXB_CSS_VALUE_INDIGO
    },
    {
        .name = (lxb_char_t *) "ivory",
        .length = 5,
        .unique = LXB_CSS_VALUE_IVORY
    },
    {
        .name = (lxb_char_t *) "khaki",
        .length = 5,
        .unique = LXB_CSS_VALUE_KHAKI
    },
    {
        .name = (lxb_char_t *) "lavender",
        .length = 8,
        .unique = LXB_CSS_VALUE_LAVENDER
    },
    {
        .name = (lxb_char_t *) "lavenderblush",
        .length = 13,
        .unique = LXB_CSS_VALUE_LAVENDERBLUSH
    },
    {
        .name = (lxb_char_t *) "lawngreen",
        .length = 9,
        .unique = LXB_CSS_VALUE_LAWNGREEN
    },
    {
        .name = (lxb_char_t *) "lemonchiffon",
        .length = 12,
        .unique = LXB_CSS_VALUE_LEMONCHIFFON
    },
    {
        .name = (lxb_char_t *) "lightblue",
        .length = 9,
        .unique = LXB_CSS_VALUE_LIGHTBLUE
    },
    {
        .name = (lxb_char_t *) "lightcoral",
        .length = 10,
        .unique = LXB_CSS_VALUE_LIGHTCORAL
    },
    {
        .name = (lxb_char_t *) "lightcyan",
        .length = 9,
        .unique = LXB_CSS_VALUE_LIGHTCYAN
    },
    {
        .name = (lxb_char_t *) "lightgoldenrodyellow",
        .length = 20,
        .unique = LXB_CSS_VALUE_LIGHTGOLDENRODYELLOW
    },
    {
        .name = (lxb_char_t *) "lightgray",
        .length = 9,
        .unique = LXB_CSS_VALUE_LIGHTGRAY
    },
    {
        .name = (lxb_char_t *) "lightgreen",
        .length = 10,
        .unique = LXB_CSS_VALUE_LIGHTGREEN
    },
    {
        .name = (lxb_char_t *) "lightgrey",
        .length = 9,
        .unique = LXB_CSS_VALUE_LIGHTGREY
    },
    {
        .name = (lxb_char_t *) "lightpink",
        .length = 9,
        .unique = LXB_CSS_VALUE_LIGHTPINK
    },
    {
        .name = (lxb_char_t *) "lightsalmon",
        .length = 11,
        .unique = LXB_CSS_VALUE_LIGHTSALMON
    },
    {
        .name = (lxb_char_t *) "lightseagreen",
        .length = 13,
        .unique = LXB_CSS_VALUE_LIGHTSEAGREEN
    },
    {
        .name = (lxb_char_t *) "lightskyblue",
        .length = 12,
        .unique = LXB_CSS_VALUE_LIGHTSKYBLUE
    },
    {
        .name = (lxb_char_t *) "lightslategray",
        .length = 14,
        .unique = LXB_CSS_VALUE_LIGHTSLATEGRAY
    },
    {
        .name = (lxb_char_t *) "lightslategrey",
        .length = 14,
        .unique = LXB_CSS_VALUE_LIGHTSLATEGREY
    },
    {
        .name = (lxb_char_t *) "lightsteelblue",
        .length = 14,
        .unique = LXB_CSS_VALUE_LIGHTSTEELBLUE
    },
    {
        .name = (lxb_char_t *) "lightyellow",
        .length = 11,
        .unique = LXB_CSS_VALUE_LIGHTYELLOW
    },
    {
        .name = (lxb_char_t *) "lime",
        .length = 4,
        .unique = LXB_CSS_VALUE_LIME
    },
    {
        .name = (lxb_char_t *) "limegreen",
        .length = 9,
        .unique = LXB_CSS_VALUE_LIMEGREEN
    },
    {
        .name = (lxb_char_t *) "linen",
        .length = 5,
        .unique = LXB_CSS_VALUE_LINEN
    },
    {
        .name = (lxb_char_t *) "magenta",
        .length = 7,
        .unique = LXB_CSS_VALUE_MAGENTA
    },
    {
        .name = (lxb_char_t *) "maroon",
        .length = 6,
        .unique = LXB_CSS_VALUE_MAROON
    },
    {
        .name = (lxb_char_t *) "mediumaquamarine",
        .length = 16,
        .unique = LXB_CSS_VALUE_MEDIUMAQUAMARINE
    },
    {
        .name = (lxb_char_t *) "mediumblue",
        .length = 10,
        .unique = LXB_CSS_VALUE_MEDIUMBLUE
    },
    {
        .name = (lxb_char_t *) "mediumorchid",
        .length = 12,
        .unique = LXB_CSS_VALUE_MEDIUMORCHID
    },
    {
        .name = (lxb_char_t *) "mediumpurple",
        .length = 12,
        .unique = LXB_CSS_VALUE_MEDIUMPURPLE
    },
    {
        .name = (lxb_char_t *) "mediumseagreen",
        .length = 14,
        .unique = LXB_CSS_VALUE_MEDIUMSEAGREEN
    },
    {
        .name = (lxb_char_t *) "mediumslateblue",
        .length = 15,
        .unique = LXB_CSS_VALUE_MEDIUMSLATEBLUE
    },
    {
        .name = (lxb_char_t *) "mediumspringgreen",
        .length = 17,
        .unique = LXB_CSS_VALUE_MEDIUMSPRINGGREEN
    },
    {
        .name = (lxb_char_t *) "mediumturquoise",
        .length = 15,
        .unique = LXB_CSS_VALUE_MEDIUMTURQUOISE
    },
    {
        .name = (lxb_char_t *) "mediumvioletred",
        .length = 15,
        .unique = LXB_CSS_VALUE_MEDIUMVIOLETRED
    },
    {
        .name = (lxb_char_t *) "midnightblue",
        .length = 12,
        .unique = LXB_CSS_VALUE_MIDNIGHTBLUE
    },
    {
        .name = (lxb_char_t *) "mintcream",
        .length = 9,
        .unique = LXB_CSS_VALUE_MINTCREAM
    },
    {
        .name = (lxb_char_t *) "mistyrose",
        .length = 9,
        .unique = LXB_CSS_VALUE_MISTYROSE
    },
    {
        .name = (lxb_char_t *) "moccasin",
        .length = 8,
        .unique = LXB_CSS_VALUE_MOCCASIN
    },
    {
        .name = (lxb_char_t *) "navajowhite",
        .length = 11,
        .unique = LXB_CSS_VALUE_NAVAJOWHITE
    },
    {
        .name = (lxb_char_t *) "navy",
        .length = 4,
        .unique = LXB_CSS_VALUE_NAVY
    },
    {
        .name = (lxb_char_t *) "oldlace",
        .length = 7,
        .unique = LXB_CSS_VALUE_OLDLACE
    },
    {
        .name = (lxb_char_t *) "olive",
        .length = 5,
        .unique = LXB_CSS_VALUE_OLIVE
    },
    {
        .name = (lxb_char_t *) "olivedrab",
        .length = 9,
        .unique = LXB_CSS_VALUE_OLIVEDRAB
    },
    {
        .name = (lxb_char_t *) "orange",
        .length = 6,
        .unique = LXB_CSS_VALUE_ORANGE
    },
    {
        .name = (lxb_char_t *) "orangered",
        .length = 9,
        .unique = LXB_CSS_VALUE_ORANGERED
    },
    {
        .name = (lxb_char_t *) "orchid",
        .length = 6,
        .unique = LXB_CSS_VALUE_ORCHID
    },
    {
        .name = (lxb_char_t *) "palegoldenrod",
        .length = 13,
        .unique = LXB_CSS_VALUE_PALEGOLDENROD
    },
    {
        .name = (lxb_char_t *) "palegreen",
        .length = 9,
        .unique = LXB_CSS_VALUE_PALEGREEN
    },
    {
        .name = (lxb_char_t *) "paleturquoise",
        .length = 13,
        .unique = LXB_CSS_VALUE_PALETURQUOISE
    },
    {
        .name = (lxb_char_t *) "palevioletred",
        .length = 13,
        .unique = LXB_CSS_VALUE_PALEVIOLETRED
    },
    {
        .name = (lxb_char_t *) "papayawhip",
        .length = 10,
        .unique = LXB_CSS_VALUE_PAPAYAWHIP
    },
    {
        .name = (lxb_char_t *) "peachpuff",
        .length = 9,
        .unique = LXB_CSS_VALUE_PEACHPUFF
    },
    {
        .name = (lxb_char_t *) "peru",
        .length = 4,
        .unique = LXB_CSS_VALUE_PERU
    },
    {
        .name = (lxb_char_t *) "pink",
        .length = 4,
        .unique = LXB_CSS_VALUE_PINK
    },
    {
        .name = (lxb_char_t *) "plum",
        .length = 4,
        .unique = LXB_CSS_VALUE_PLUM
    },
    {
        .name = (lxb_char_t *) "powderblue",
        .length = 10,
        .unique = LXB_CSS_VALUE_POWDERBLUE
    },
    {
        .name = (lxb_char_t *) "purple",
        .length = 6,
        .unique = LXB_CSS_VALUE_PURPLE
    },
    {
        .name = (lxb_char_t *) "rebeccapurple",
        .length = 13,
        .unique = LXB_CSS_VALUE_REBECCAPURPLE
    },
    {
        .name = (lxb_char_t *) "red",
        .length = 3,
        .unique = LXB_CSS_VALUE_RED
    },
    {
        .name = (lxb_char_t *) "rosybrown",
        .length = 9,
        .unique = LXB_CSS_VALUE_ROSYBROWN
    },
    {
        .name = (lxb_char_t *) "royalblue",
        .length = 9,
        .unique = LXB_CSS_VALUE_ROYALBLUE
    },
    {
        .name = (lxb_char_t *) "saddlebrown",
        .length = 11,
        .unique = LXB_CSS_VALUE_SADDLEBROWN
    },
    {
        .name = (lxb_char_t *) "salmon",
        .length = 6,
        .unique = LXB_CSS_VALUE_SALMON
    },
    {
        .name = (lxb_char_t *) "sandybrown",
        .length = 10,
        .unique = LXB_CSS_VALUE_SANDYBROWN
    },
    {
        .name = (lxb_char_t *) "seagreen",
        .length = 8,
        .unique = LXB_CSS_VALUE_SEAGREEN
    },
    {
        .name = (lxb_char_t *) "seashell",
        .length = 8,
        .unique = LXB_CSS_VALUE_SEASHELL
    },
    {
        .name = (lxb_char_t *) "sienna",
        .length = 6,
        .unique = LXB_CSS_VALUE_SIENNA
    },
    {
        .name = (lxb_char_t *) "silver",
        .length = 6,
        .unique = LXB_CSS_VALUE_SILVER
    },
    {
        .name = (lxb_char_t *) "skyblue",
        .length = 7,
        .unique = LXB_CSS_VALUE_SKYBLUE
    },
    {
        .name = (lxb_char_t *) "slateblue",
        .length = 9,
        .unique = LXB_CSS_VALUE_SLATEBLUE
    },
    {
        .name = (lxb_char_t *) "slategray",
        .length = 9,
        .unique = LXB_CSS_VALUE_SLATEGRAY
    },
    {
        .name = (lxb_char_t *) "slategrey",
        .length = 9,
        .unique = LXB_CSS_VALUE_SLATEGREY
    },
    {
        .name = (lxb_char_t *) "snow",
        .length = 4,
        .unique = LXB_CSS_VALUE_SNOW
    },
    {
        .name = (lxb_char_t *) "springgreen",
        .length = 11,
        .unique = LXB_CSS_VALUE_SPRINGGREEN
    },
    {
        .name = (lxb_char_t *) "steelblue",
        .length = 9,
        .unique = LXB_CSS_VALUE_STEELBLUE
    },
    {
        .name = (lxb_char_t *) "tan",
        .length = 3,
        .unique = LXB_CSS_VALUE_TAN
    },
    {
        .name = (lxb_char_t *) "teal",
        .length = 4,
        .unique = LXB_CSS_VALUE_TEAL
    },
    {
        .name = (lxb_char_t *) "thistle",
        .length = 7,
        .unique = LXB_CSS_VALUE_THISTLE
    },
    {
        .name = (lxb_char_t *) "tomato",
        .length = 6,
        .unique = LXB_CSS_VALUE_TOMATO
    },
    {
        .name = (lxb_char_t *) "turquoise",
        .length = 9,
        .unique = LXB_CSS_VALUE_TURQUOISE
    },
    {
        .name = (lxb_char_t *) "violet",
        .length = 6,
        .unique = LXB_CSS_VALUE_VIOLET
    },
    {
        .name = (lxb_char_t *) "wheat",
        .length = 5,
        .unique = LXB_CSS_VALUE_WHEAT
    },
    {
        .name = (lxb_char_t *) "white",
        .length = 5,
        .unique = LXB_CSS_VALUE_WHITE
    },
    {
        .name = (lxb_char_t *) "whitesmoke",
        .length = 10,
        .unique = LXB_CSS_VALUE_WHITESMOKE
    },
    {
        .name = (lxb_char_t *) "yellow",
        .length = 6,
        .unique = LXB_CSS_VALUE_YELLOW
    },
    {
        .name = (lxb_char_t *) "yellowgreen",
        .length = 11,
        .unique = LXB_CSS_VALUE_YELLOWGREEN
    },
    {
        .name = (lxb_char_t *) "Canvas",
        .length = 6,
        .unique = LXB_CSS_VALUE_CANVAS
    },
    {
        .name = (lxb_char_t *) "CanvasText",
        .length = 10,
        .unique = LXB_CSS_VALUE_CANVASTEXT
    },
    {
        .name = (lxb_char_t *) "LinkText",
        .length = 8,
        .unique = LXB_CSS_VALUE_LINKTEXT
    },
    {
        .name = (lxb_char_t *) "VisitedText",
        .length = 11,
        .unique = LXB_CSS_VALUE_VISITEDTEXT
    },
    {
        .name = (lxb_char_t *) "ActiveText",
        .length = 10,
        .unique = LXB_CSS_VALUE_ACTIVETEXT
    },
    {
        .name = (lxb_char_t *) "ButtonFace",
        .length = 10,
        .unique = LXB_CSS_VALUE_BUTTONFACE
    },
    {
        .name = (lxb_char_t *) "ButtonText",
        .length = 10,
        .unique = LXB_CSS_VALUE_BUTTONTEXT
    },
    {
        .name = (lxb_char_t *) "ButtonBorder",
        .length = 12,
        .unique = LXB_CSS_VALUE_BUTTONBORDER
    },
    {
        .name = (lxb_char_t *) "Field",
        .length = 5,
        .unique = LXB_CSS_VALUE_FIELD
    },
    {
        .name = (lxb_char_t *) "FieldText",
        .length = 9,
        .unique = LXB_CSS_VALUE_FIELDTEXT
    },
    {
        .name = (lxb_char_t *) "Highlight",
        .length = 9,
        .unique = LXB_CSS_VALUE_HIGHLIGHT
    },
    {
        .name = (lxb_char_t *) "HighlightText",
        .length = 13,
        .unique = LXB_CSS_VALUE_HIGHLIGHTTEXT
    },
    {
        .name = (lxb_char_t *) "SelectedItem",
        .length = 12,
        .unique = LXB_CSS_VALUE_SELECTEDITEM
    },
    {
        .name = (lxb_char_t *) "SelectedItemText",
        .length = 16,
        .unique = LXB_CSS_VALUE_SELECTEDITEMTEXT
    },
    {
        .name = (lxb_char_t *) "Mark",
        .length = 4,
        .unique = LXB_CSS_VALUE_MARK
    },
    {
        .name = (lxb_char_t *) "MarkText",
        .length = 8,
        .unique = LXB_CSS_VALUE_MARKTEXT
    },
    {
        .name = (lxb_char_t *) "GrayText",
        .length = 8,
        .unique = LXB_CSS_VALUE_GRAYTEXT
    },
    {
        .name = (lxb_char_t *) "AccentColor",
        .length = 11,
        .unique = LXB_CSS_VALUE_ACCENTCOLOR
    },
    {
        .name = (lxb_char_t *) "AccentColorText",
        .length = 15,
        .unique = LXB_CSS_VALUE_ACCENTCOLORTEXT
    },
    {
        .name = (lxb_char_t *) "rgb",
        .length = 3,
        .unique = LXB_CSS_VALUE_RGB
    },
    {
        .name = (lxb_char_t *) "rgba",
        .length = 4,
        .unique = LXB_CSS_VALUE_RGBA
    },
    {
        .name = (lxb_char_t *) "hsl",
        .length = 3,
        .unique = LXB_CSS_VALUE_HSL
    },
    {
        .name = (lxb_char_t *) "hsla",
        .length = 4,
        .unique = LXB_CSS_VALUE_HSLA
    },
    {
        .name = (lxb_char_t *) "hwb",
        .length = 3,
        .unique = LXB_CSS_VALUE_HWB
    },
    {
        .name = (lxb_char_t *) "lab",
        .length = 3,
        .unique = LXB_CSS_VALUE_LAB
    },
    {
        .name = (lxb_char_t *) "lch",
        .length = 3,
        .unique = LXB_CSS_VALUE_LCH
    },
    {
        .name = (lxb_char_t *) "oklab",
        .length = 5,
        .unique = LXB_CSS_VALUE_OKLAB
    },
    {
        .name = (lxb_char_t *) "oklch",
        .length = 5,
        .unique = LXB_CSS_VALUE_OKLCH
    },
    {
        .name = (lxb_char_t *) "color",
        .length = 5,
        .unique = LXB_CSS_VALUE_COLOR
    },
    {
        .name = (lxb_char_t *) "ltr",
        .length = 3,
        .unique = LXB_CSS_VALUE_LTR
    },
    {
        .name = (lxb_char_t *) "rtl",
        .length = 3,
        .unique = LXB_CSS_VALUE_RTL
    },
    {
        .name = (lxb_char_t *) "block",
        .length = 5,
        .unique = LXB_CSS_VALUE_BLOCK
    },
    {
        .name = (lxb_char_t *) "inline",
        .length = 6,
        .unique = LXB_CSS_VALUE_INLINE
    },
    {
        .name = (lxb_char_t *) "run-in",
        .length = 6,
        .unique = LXB_CSS_VALUE_RUN_IN
    },
    {
        .name = (lxb_char_t *) "flow",
        .length = 4,
        .unique = LXB_CSS_VALUE_FLOW
    },
    {
        .name = (lxb_char_t *) "flow-root",
        .length = 9,
        .unique = LXB_CSS_VALUE_FLOW_ROOT
    },
    {
        .name = (lxb_char_t *) "table",
        .length = 5,
        .unique = LXB_CSS_VALUE_TABLE
    },
    {
        .name = (lxb_char_t *) "flex",
        .length = 4,
        .unique = LXB_CSS_VALUE_FLEX
    },
    {
        .name = (lxb_char_t *) "grid",
        .length = 4,
        .unique = LXB_CSS_VALUE_GRID
    },
    {
        .name = (lxb_char_t *) "ruby",
        .length = 4,
        .unique = LXB_CSS_VALUE_RUBY
    },
    {
        .name = (lxb_char_t *) "list-item",
        .length = 9,
        .unique = LXB_CSS_VALUE_LIST_ITEM
    },
    {
        .name = (lxb_char_t *) "table-row-group",
        .length = 15,
        .unique = LXB_CSS_VALUE_TABLE_ROW_GROUP
    },
    {
        .name = (lxb_char_t *) "table-header-group",
        .length = 18,
        .unique = LXB_CSS_VALUE_TABLE_HEADER_GROUP
    },
    {
        .name = (lxb_char_t *) "table-footer-group",
        .length = 18,
        .unique = LXB_CSS_VALUE_TABLE_FOOTER_GROUP
    },
    {
        .name = (lxb_char_t *) "table-row",
        .length = 9,
        .unique = LXB_CSS_VALUE_TABLE_ROW
    },
    {
        .name = (lxb_char_t *) "table-cell",
        .length = 10,
        .unique = LXB_CSS_VALUE_TABLE_CELL
    },
    {
        .name = (lxb_char_t *) "table-column-group",
        .length = 18,
        .unique = LXB_CSS_VALUE_TABLE_COLUMN_GROUP
    },
    {
        .name = (lxb_char_t *) "table-column",
        .length = 12,
        .unique = LXB_CSS_VALUE_TABLE_COLUMN
    },
    {
        .name = (lxb_char_t *) "table-caption",
        .length = 13,
        .unique = LXB_CSS_VALUE_TABLE_CAPTION
    },
    {
        .name = (lxb_char_t *) "ruby-base",
        .length = 9,
        .unique = LXB_CSS_VALUE_RUBY_BASE
    },
    {
        .name = (lxb_char_t *) "ruby-text",
        .length = 9,
        .unique = LXB_CSS_VALUE_RUBY_TEXT
    },
    {
        .name = (lxb_char_t *) "ruby-base-container",
        .length = 19,
        .unique = LXB_CSS_VALUE_RUBY_BASE_CONTAINER
    },
    {
        .name = (lxb_char_t *) "ruby-text-container",
        .length = 19,
        .unique = LXB_CSS_VALUE_RUBY_TEXT_CONTAINER
    },
    {
        .name = (lxb_char_t *) "contents",
        .length = 8,
        .unique = LXB_CSS_VALUE_CONTENTS
    },
    {
        .name = (lxb_char_t *) "inline-block",
        .length = 12,
        .unique = LXB_CSS_VALUE_INLINE_BLOCK
    },
    {
        .name = (lxb_char_t *) "inline-table",
        .length = 12,
        .unique = LXB_CSS_VALUE_INLINE_TABLE
    },
    {
        .name = (lxb_char_t *) "inline-flex",
        .length = 11,
        .unique = LXB_CSS_VALUE_INLINE_FLEX
    },
    {
        .name = (lxb_char_t *) "inline-grid",
        .length = 11,
        .unique = LXB_CSS_VALUE_INLINE_GRID
    },
    {
        .name = (lxb_char_t *) "hanging",
        .length = 7,
        .unique = LXB_CSS_VALUE_HANGING
    },
    {
        .name = (lxb_char_t *) "content",
        .length = 7,
        .unique = LXB_CSS_VALUE_CONTENT
    },
    {
        .name = (lxb_char_t *) "row",
        .length = 3,
        .unique = LXB_CSS_VALUE_ROW
    },
    {
        .name = (lxb_char_t *) "row-reverse",
        .length = 11,
        .unique = LXB_CSS_VALUE_ROW_REVERSE
    },
    {
        .name = (lxb_char_t *) "column",
        .length = 6,
        .unique = LXB_CSS_VALUE_COLUMN
    },
    {
        .name = (lxb_char_t *) "column-reverse",
        .length = 14,
        .unique = LXB_CSS_VALUE_COLUMN_REVERSE
    },
    {
        .name = (lxb_char_t *) "_number",
        .length = 7,
        .unique = LXB_CSS_VALUE__NUMBER
    },
    {
        .name = (lxb_char_t *) "nowrap",
        .length = 6,
        .unique = LXB_CSS_VALUE_NOWRAP
    },
    {
        .name = (lxb_char_t *) "wrap",
        .length = 4,
        .unique = LXB_CSS_VALUE_WRAP
    },
    {
        .name = (lxb_char_t *) "wrap-reverse",
        .length = 12,
        .unique = LXB_CSS_VALUE_WRAP_REVERSE
    },
    {
        .name = (lxb_char_t *) "snap-block",
        .length = 10,
        .unique = LXB_CSS_VALUE_SNAP_BLOCK
    },
    {
        .name = (lxb_char_t *) "start",
        .length = 5,
        .unique = LXB_CSS_VALUE_START
    },
    {
        .name = (lxb_char_t *) "end",
        .length = 3,
        .unique = LXB_CSS_VALUE_END
    },
    {
        .name = (lxb_char_t *) "near",
        .length = 4,
        .unique = LXB_CSS_VALUE_NEAR
    },
    {
        .name = (lxb_char_t *) "snap-inline",
        .length = 11,
        .unique = LXB_CSS_VALUE_SNAP_INLINE
    },
    {
        .name = (lxb_char_t *) "_integer",
        .length = 8,
        .unique = LXB_CSS_VALUE__INTEGER
    },
    {
        .name = (lxb_char_t *) "region",
        .length = 6,
        .unique = LXB_CSS_VALUE_REGION
    },
    {
        .name = (lxb_char_t *) "page",
        .length = 4,
        .unique = LXB_CSS_VALUE_PAGE
    },
    {
        .name = (lxb_char_t *) "serif",
        .length = 5,
        .unique = LXB_CSS_VALUE_SERIF
    },
    {
        .name = (lxb_char_t *) "sans-serif",
        .length = 10,
        .unique = LXB_CSS_VALUE_SANS_SERIF
    },
    {
        .name = (lxb_char_t *) "cursive",
        .length = 7,
        .unique = LXB_CSS_VALUE_CURSIVE
    },
    {
        .name = (lxb_char_t *) "fantasy",
        .length = 7,
        .unique = LXB_CSS_VALUE_FANTASY
    },
    {
        .name = (lxb_char_t *) "monospace",
        .length = 9,
        .unique = LXB_CSS_VALUE_MONOSPACE
    },
    {
        .name = (lxb_char_t *) "system-ui",
        .length = 9,
        .unique = LXB_CSS_VALUE_SYSTEM_UI
    },
    {
        .name = (lxb_char_t *) "emoji",
        .length = 5,
        .unique = LXB_CSS_VALUE_EMOJI
    },
    {
        .name = (lxb_char_t *) "math",
        .length = 4,
        .unique = LXB_CSS_VALUE_MATH
    },
    {
        .name = (lxb_char_t *) "fangsong",
        .length = 8,
        .unique = LXB_CSS_VALUE_FANGSONG
    },
    {
        .name = (lxb_char_t *) "ui-serif",
        .length = 8,
        .unique = LXB_CSS_VALUE_UI_SERIF
    },
    {
        .name = (lxb_char_t *) "ui-sans-serif",
        .length = 13,
        .unique = LXB_CSS_VALUE_UI_SANS_SERIF
    },
    {
        .name = (lxb_char_t *) "ui-monospace",
        .length = 12,
        .unique = LXB_CSS_VALUE_UI_MONOSPACE
    },
    {
        .name = (lxb_char_t *) "ui-rounded",
        .length = 10,
        .unique = LXB_CSS_VALUE_UI_ROUNDED
    },
    {
        .name = (lxb_char_t *) "xx-small",
        .length = 8,
        .unique = LXB_CSS_VALUE_XX_SMALL
    },
    {
        .name = (lxb_char_t *) "x-small",
        .length = 7,
        .unique = LXB_CSS_VALUE_X_SMALL
    },
    {
        .name = (lxb_char_t *) "small",
        .length = 5,
        .unique = LXB_CSS_VALUE_SMALL
    },
    {
        .name = (lxb_char_t *) "large",
        .length = 5,
        .unique = LXB_CSS_VALUE_LARGE
    },
    {
        .name = (lxb_char_t *) "x-large",
        .length = 7,
        .unique = LXB_CSS_VALUE_X_LARGE
    },
    {
        .name = (lxb_char_t *) "xx-large",
        .length = 8,
        .unique = LXB_CSS_VALUE_XX_LARGE
    },
    {
        .name = (lxb_char_t *) "xxx-large",
        .length = 9,
        .unique = LXB_CSS_VALUE_XXX_LARGE
    },
    {
        .name = (lxb_char_t *) "larger",
        .length = 6,
        .unique = LXB_CSS_VALUE_LARGER
    },
    {
        .name = (lxb_char_t *) "smaller",
        .length = 7,
        .unique = LXB_CSS_VALUE_SMALLER
    },
    {
        .name = (lxb_char_t *) "normal",
        .length = 6,
        .unique = LXB_CSS_VALUE_NORMAL
    },
    {
        .name = (lxb_char_t *) "ultra-condensed",
        .length = 15,
        .unique = LXB_CSS_VALUE_ULTRA_CONDENSED
    },
    {
        .name = (lxb_char_t *) "extra-condensed",
        .length = 15,
        .unique = LXB_CSS_VALUE_EXTRA_CONDENSED
    },
    {
        .name = (lxb_char_t *) "condensed",
        .length = 9,
        .unique = LXB_CSS_VALUE_CONDENSED
    },
    {
        .name = (lxb_char_t *) "semi-condensed",
        .length = 14,
        .unique = LXB_CSS_VALUE_SEMI_CONDENSED
    },
    {
        .name = (lxb_char_t *) "semi-expanded",
        .length = 13,
        .unique = LXB_CSS_VALUE_SEMI_EXPANDED
    },
    {
        .name = (lxb_char_t *) "expanded",
        .length = 8,
        .unique = LXB_CSS_VALUE_EXPANDED
    },
    {
        .name = (lxb_char_t *) "extra-expanded",
        .length = 14,
        .unique = LXB_CSS_VALUE_EXTRA_EXPANDED
    },
    {
        .name = (lxb_char_t *) "ultra-expanded",
        .length = 14,
        .unique = LXB_CSS_VALUE_ULTRA_EXPANDED
    },
    {
        .name = (lxb_char_t *) "italic",
        .length = 6,
        .unique = LXB_CSS_VALUE_ITALIC
    },
    {
        .name = (lxb_char_t *) "oblique",
        .length = 7,
        .unique = LXB_CSS_VALUE_OBLIQUE
    },
    {
        .name = (lxb_char_t *) "bold",
        .length = 4,
        .unique = LXB_CSS_VALUE_BOLD
    },
    {
        .name = (lxb_char_t *) "bolder",
        .length = 6,
        .unique = LXB_CSS_VALUE_BOLDER
    },
    {
        .name = (lxb_char_t *) "lighter",
        .length = 7,
        .unique = LXB_CSS_VALUE_LIGHTER
    },
    {
        .name = (lxb_char_t *) "force-end",
        .length = 9,
        .unique = LXB_CSS_VALUE_FORCE_END
    },
    {
        .name = (lxb_char_t *) "allow-end",
        .length = 9,
        .unique = LXB_CSS_VALUE_ALLOW_END
    },
    {
        .name = (lxb_char_t *) "min-content",
        .length = 11,
        .unique = LXB_CSS_VALUE_MIN_CONTENT
    },
    {
        .name = (lxb_char_t *) "max-content",
        .length = 11,
        .unique = LXB_CSS_VALUE_MAX_CONTENT
    },
    {
        .name = (lxb_char_t *) "_angle",
        .length = 6,
        .unique = LXB_CSS_VALUE__ANGLE
    },
    {
        .name = (lxb_char_t *) "manual",
        .length = 6,
        .unique = LXB_CSS_VALUE_MANUAL
    },
    {
        .name = (lxb_char_t *) "loose",
        .length = 5,
        .unique = LXB_CSS_VALUE_LOOSE
    },
    {
        .name = (lxb_char_t *) "strict",
        .length = 6,
        .unique = LXB_CSS_VALUE_STRICT
    },
    {
        .name = (lxb_char_t *) "anywhere",
        .length = 8,
        .unique = LXB_CSS_VALUE_ANYWHERE
    },
    {
        .name = (lxb_char_t *) "visible",
        .length = 7,
        .unique = LXB_CSS_VALUE_VISIBLE
    },
    {
        .name = (lxb_char_t *) "clip",
        .length = 4,
        .unique = LXB_CSS_VALUE_CLIP
    },
    {
        .name = (lxb_char_t *) "scroll",
        .length = 6,
        .unique = LXB_CSS_VALUE_SCROLL
    },
    {
        .name = (lxb_char_t *) "break-word",
        .length = 10,
        .unique = LXB_CSS_VALUE_BREAK_WORD
    },
    {
        .name = (lxb_char_t *) "static",
        .length = 6,
        .unique = LXB_CSS_VALUE_STATIC
    },
    {
        .name = (lxb_char_t *) "relative",
        .length = 8,
        .unique = LXB_CSS_VALUE_RELATIVE
    },
    {
        .name = (lxb_char_t *) "absolute",
        .length = 8,
        .unique = LXB_CSS_VALUE_ABSOLUTE
    },
    {
        .name = (lxb_char_t *) "sticky",
        .length = 6,
        .unique = LXB_CSS_VALUE_STICKY
    },
    {
        .name = (lxb_char_t *) "fixed",
        .length = 5,
        .unique = LXB_CSS_VALUE_FIXED
    },
    {
        .name = (lxb_char_t *) "justify",
        .length = 7,
        .unique = LXB_CSS_VALUE_JUSTIFY
    },
    {
        .name = (lxb_char_t *) "match-parent",
        .length = 12,
        .unique = LXB_CSS_VALUE_MATCH_PARENT
    },
    {
        .name = (lxb_char_t *) "justify-all",
        .length = 11,
        .unique = LXB_CSS_VALUE_JUSTIFY_ALL
    },
    {
        .name = (lxb_char_t *) "all",
        .length = 3,
        .unique = LXB_CSS_VALUE_ALL
    },
    {
        .name = (lxb_char_t *) "digits",
        .length = 6,
        .unique = LXB_CSS_VALUE_DIGITS
    },
    {
        .name = (lxb_char_t *) "underline",
        .length = 9,
        .unique = LXB_CSS_VALUE_UNDERLINE
    },
    {
        .name = (lxb_char_t *) "overline",
        .length = 8,
        .unique = LXB_CSS_VALUE_OVERLINE
    },
    {
        .name = (lxb_char_t *) "line-through",
        .length = 12,
        .unique = LXB_CSS_VALUE_LINE_THROUGH
    },
    {
        .name = (lxb_char_t *) "blink",
        .length = 5,
        .unique = LXB_CSS_VALUE_BLINK
    },
    {
        .name = (lxb_char_t *) "wavy",
        .length = 4,
        .unique = LXB_CSS_VALUE_WAVY
    },
    {
        .name = (lxb_char_t *) "each-line",
        .length = 9,
        .unique = LXB_CSS_VALUE_EACH_LINE
    },
    {
        .name = (lxb_char_t *) "inter-word",
        .length = 10,
        .unique = LXB_CSS_VALUE_INTER_WORD
    },
    {
        .name = (lxb_char_t *) "inter-character",
        .length = 15,
        .unique = LXB_CSS_VALUE_INTER_CHARACTER
    },
    {
        .name = (lxb_char_t *) "mixed",
        .length = 5,
        .unique = LXB_CSS_VALUE_MIXED
    },
    {
        .name = (lxb_char_t *) "upright",
        .length = 7,
        .unique = LXB_CSS_VALUE_UPRIGHT
    },
    {
        .name = (lxb_char_t *) "sideways",
        .length = 8,
        .unique = LXB_CSS_VALUE_SIDEWAYS
    },
    {
        .name = (lxb_char_t *) "ellipsis",
        .length = 8,
        .unique = LXB_CSS_VALUE_ELLIPSIS
    },
    {
        .name = (lxb_char_t *) "capitalize",
        .length = 10,
        .unique = LXB_CSS_VALUE_CAPITALIZE
    },
    {
        .name = (lxb_char_t *) "uppercase",
        .length = 9,
        .unique = LXB_CSS_VALUE_UPPERCASE
    },
    {
        .name = (lxb_char_t *) "lowercase",
        .length = 9,
        .unique = LXB_CSS_VALUE_LOWERCASE
    },
    {
        .name = (lxb_char_t *) "full-width",
        .length = 10,
        .unique = LXB_CSS_VALUE_FULL_WIDTH
    },
    {
        .name = (lxb_char_t *) "full-size-kana",
        .length = 14,
        .unique = LXB_CSS_VALUE_FULL_SIZE_KANA
    },
    {
        .name = (lxb_char_t *) "embed",
        .length = 5,
        .unique = LXB_CSS_VALUE_EMBED
    },
    {
        .name = (lxb_char_t *) "isolate",
        .length = 7,
        .unique = LXB_CSS_VALUE_ISOLATE
    },
    {
        .name = (lxb_char_t *) "bidi-override",
        .length = 13,
        .unique = LXB_CSS_VALUE_BIDI_OVERRIDE
    },
    {
        .name = (lxb_char_t *) "isolate-override",
        .length = 16,
        .unique = LXB_CSS_VALUE_ISOLATE_OVERRIDE
    },
    {
        .name = (lxb_char_t *) "plaintext",
        .length = 9,
        .unique = LXB_CSS_VALUE_PLAINTEXT
    },
    {
        .name = (lxb_char_t *) "collapse",
        .length = 8,
        .unique = LXB_CSS_VALUE_COLLAPSE
    },
    {
        .name = (lxb_char_t *) "pre",
        .length = 3,
        .unique = LXB_CSS_VALUE_PRE
    },
    {
        .name = (lxb_char_t *) "pre-wrap",
        .length = 8,
        .unique = LXB_CSS_VALUE_PRE_WRAP
    },
    {
        .name = (lxb_char_t *) "break-spaces",
        .length = 12,
        .unique = LXB_CSS_VALUE_BREAK_SPACES
    },
    {
        .name = (lxb_char_t *) "pre-line",
        .length = 8,
        .unique = LXB_CSS_VALUE_PRE_LINE
    },
    {
        .name = (lxb_char_t *) "keep-all",
        .length = 8,
        .unique = LXB_CSS_VALUE_KEEP_ALL
    },
    {
        .name = (lxb_char_t *) "break-all",
        .length = 9,
        .unique = LXB_CSS_VALUE_BREAK_ALL
    },
    {
        .name = (lxb_char_t *) "both",
        .length = 4,
        .unique = LXB_CSS_VALUE_BOTH
    },
    {
        .name = (lxb_char_t *) "minimum",
        .length = 7,
        .unique = LXB_CSS_VALUE_MINIMUM
    },
    {
        .name = (lxb_char_t *) "maximum",
        .length = 7,
        .unique = LXB_CSS_VALUE_MAXIMUM
    },
    {
        .name = (lxb_char_t *) "clear",
        .length = 5,
        .unique = LXB_CSS_VALUE_CLEAR
    },
    {
        .name = (lxb_char_t *) "horizontal-tb",
        .length = 13,
        .unique = LXB_CSS_VALUE_HORIZONTAL_TB
    },
    {
        .name = (lxb_char_t *) "vertical-rl",
        .length = 11,
        .unique = LXB_CSS_VALUE_VERTICAL_RL
    },
    {
        .name = (lxb_char_t *) "vertical-lr",
        .length = 11,
        .unique = LXB_CSS_VALUE_VERTICAL_LR
    },
    {
        .name = (lxb_char_t *) "sideways-rl",
        .length = 11,
        .unique = LXB_CSS_VALUE_SIDEWAYS_RL
    },
    {
        .name = (lxb_char_t *) "sideways-lr",
        .length = 11,
        .unique = LXB_CSS_VALUE_SIDEWAYS_LR
    }
};

static const lexbor_shs_entry_t lxb_css_value_shs[373] = 
{
    {NULL, NULL, 253, 0}, 
    {"salmon", (void *) LXB_CSS_VALUE_SALMON, 6, 2}, 
    {"canvas", (void *) LXB_CSS_VALUE_CANVAS, 6, 4}, 
    {"allow-end", (void *) LXB_CSS_VALUE_ALLOW_END, 9, 0}, 
    {"static", (void *) LXB_CSS_VALUE_STATIC, 6, 5}, 
    {"sticky", (void *) LXB_CSS_VALUE_STICKY, 6, 0}, 
    {"darkviolet", (void *) LXB_CSS_VALUE_DARKVIOLET, 10, 0}, 
    {"blue", (void *) LXB_CSS_VALUE_BLUE, 4, 1}, 
    {"end", (void *) LXB_CSS_VALUE_END, 3, 24}, 
    {"middle", (void *) LXB_CSS_VALUE_MIDDLE, 6, 32}, 
    {"rgb", (void *) LXB_CSS_VALUE_RGB, 3, 59}, 
    {"baseline", (void *) LXB_CSS_VALUE_BASELINE, 8, 69}, 
    {"mistyrose", (void *) LXB_CSS_VALUE_MISTYROSE, 9, 71}, 
    {"expanded", (void *) LXB_CSS_VALUE_EXPANDED, 8, 92}, 
    {"space-between", (void *) LXB_CSS_VALUE_SPACE_BETWEEN, 13, 0}, 
    {"mediumpurple", (void *) LXB_CSS_VALUE_MEDIUMPURPLE, 12, 99}, 
    {"bidi-override", (void *) LXB_CSS_VALUE_BIDI_OVERRIDE, 13, 0}, 
    {"bold", (void *) LXB_CSS_VALUE_BOLD, 4, 103}, 
    {"mixed", (void *) LXB_CSS_VALUE_MIXED, 5, 105}, 
    {"extra-expanded", (void *) LXB_CSS_VALUE_EXTRA_EXPANDED, 14, 119}, 
    {"auto", (void *) LXB_CSS_VALUE_AUTO, 4, 129}, 
    {"teal", (void *) LXB_CSS_VALUE_TEAL, 4, 130}, 
    {"lab", (void *) LXB_CSS_VALUE_LAB, 3, 131}, 
    {"break-word", (void *) LXB_CSS_VALUE_BREAK_WORD, 10, 0}, 
    {"beige", (void *) LXB_CSS_VALUE_BEIGE, 5, 0}, 
    {"mediumorchid", (void *) LXB_CSS_VALUE_MEDIUMORCHID, 12, 0}, 
    {"vertical-lr", (void *) LXB_CSS_VALUE_VERTICAL_LR, 11, 0}, 
    {"table-cell", (void *) LXB_CSS_VALUE_TABLE_CELL, 10, 135}, 
    {"pre-wrap", (void *) LXB_CSS_VALUE_PRE_WRAP, 8, 136}, 
    {"super", (void *) LXB_CSS_VALUE_SUPER, 5, 0}, 
    {"silver", (void *) LXB_CSS_VALUE_SILVER, 6, 137}, 
    {"hsl", (void *) LXB_CSS_VALUE_HSL, 3, 140}, 
    {"bisque", (void *) LXB_CSS_VALUE_BISQUE, 6, 53}, 
    {"darkblue", (void *) LXB_CSS_VALUE_DARKBLUE, 8, 0}, 
    {"hex", (void *) LXB_CSS_VALUE_HEX, 3, 0}, 
    {"darkorange", (void *) LXB_CSS_VALUE_DARKORANGE, 10, 143}, 
    {"lightcoral", (void *) LXB_CSS_VALUE_LIGHTCORAL, 10, 145}, 
    {"table-row", (void *) LXB_CSS_VALUE_TABLE_ROW, 9, 0}, 
    {"ridge", (void *) LXB_CSS_VALUE_RIDGE, 5, 149}, 
    {"violet", (void *) LXB_CSS_VALUE_VIOLET, 6, 156}, 
    {"italic", (void *) LXB_CSS_VALUE_ITALIC, 6, 157}, 
    {"relative", (void *) LXB_CSS_VALUE_RELATIVE, 8, 0}, 
    {"royalblue", (void *) LXB_CSS_VALUE_ROYALBLUE, 9, 179}, 
    {"highlighttext", (void *) LXB_CSS_VALUE_HIGHLIGHTTEXT, 13, 0}, 
    {"visitedtext", (void *) LXB_CSS_VALUE_VISITEDTEXT, 11, 193}, 
    {"ideographic", (void *) LXB_CSS_VALUE_IDEOGRAPHIC, 11, 0}, 
    {"outset", (void *) LXB_CSS_VALUE_OUTSET, 6, 194}, 
    {"azure", (void *) LXB_CSS_VALUE_AZURE, 5, 0}, 
    {"pink", (void *) LXB_CSS_VALUE_PINK, 4, 0}, 
    {"near", (void *) LXB_CSS_VALUE_NEAR, 4, 0}, 
    {"magenta", (void *) LXB_CSS_VALUE_MAGENTA, 7, 204}, 
    {"aliceblue", (void *) LXB_CSS_VALUE_ALICEBLUE, 9, 0}, 
    {"aquamarine", (void *) LXB_CSS_VALUE_AQUAMARINE, 10, 0}, 
    {"seagreen", (void *) LXB_CSS_VALUE_SEAGREEN, 8, 55}, 
    {"antiquewhite", (void *) LXB_CSS_VALUE_ANTIQUEWHITE, 12, 0}, 
    {"contents", (void *) LXB_CSS_VALUE_CONTENTS, 8, 56}, 
    {"lightpink", (void *) LXB_CSS_VALUE_LIGHTPINK, 9, 0}, 
    {"snap-block", (void *) LXB_CSS_VALUE_SNAP_BLOCK, 10, 0}, 
    {"white", (void *) LXB_CSS_VALUE_WHITE, 5, 0}, 
    {"embed", (void *) LXB_CSS_VALUE_EMBED, 5, 66}, 
    {"first", (void *) LXB_CSS_VALUE_FIRST, 5, 211}, 
    {"groove", (void *) LXB_CSS_VALUE_GROOVE, 6, 212}, 
    {"normal", (void *) LXB_CSS_VALUE_NORMAL, 6, 0}, 
    {"whitesmoke", (void *) LXB_CSS_VALUE_WHITESMOKE, 10, 0}, 
    {"fieldtext", (void *) LXB_CSS_VALUE_FIELDTEXT, 9, 221}, 
    {"flex-start", (void *) LXB_CSS_VALUE_FLEX_START, 10, 227}, 
    {"slategray", (void *) LXB_CSS_VALUE_SLATEGRAY, 9, 67}, 
    {"slategrey", (void *) LXB_CSS_VALUE_SLATEGREY, 9, 68}, 
    {"darkmagenta", (void *) LXB_CSS_VALUE_DARKMAGENTA, 11, 0}, 
    {"sandybrown", (void *) LXB_CSS_VALUE_SANDYBROWN, 10, 0}, 
    {"field", (void *) LXB_CSS_VALUE_FIELD, 5, 234}, 
    {"monospace", (void *) LXB_CSS_VALUE_MONOSPACE, 9, 78}, 
    {"color", (void *) LXB_CSS_VALUE_COLOR, 5, 236}, 
    {"center", (void *) LXB_CSS_VALUE_CENTER, 6, 240}, 
    {"force-end", (void *) LXB_CSS_VALUE_FORCE_END, 9, 0}, 
    {"solid", (void *) LXB_CSS_VALUE_SOLID, 5, 243}, 
    {"gold", (void *) LXB_CSS_VALUE_GOLD, 4, 248}, 
    {"peachpuff", (void *) LXB_CSS_VALUE_PEACHPUFF, 9, 0}, 
    {"saddlebrown", (void *) LXB_CSS_VALUE_SADDLEBROWN, 11, 86}, 
    {"inline", (void *) LXB_CSS_VALUE_INLINE, 6, 254}, 
    {"isolate", (void *) LXB_CSS_VALUE_ISOLATE, 7, 0}, 
    {"goldenrod", (void *) LXB_CSS_VALUE_GOLDENROD, 9, 0}, 
    {"cyan", (void *) LXB_CSS_VALUE_CYAN, 4, 256}, 
    {"linen", (void *) LXB_CSS_VALUE_LINEN, 5, 257}, 
    {"column", (void *) LXB_CSS_VALUE_COLUMN, 6, 258}, 
    {"crimson", (void *) LXB_CSS_VALUE_CRIMSON, 7, 259}, 
    {"springgreen", (void *) LXB_CSS_VALUE_SPRINGGREEN, 11, 0}, 
    {"lawngreen", (void *) LXB_CSS_VALUE_LAWNGREEN, 9, 260}, 
    {"lightgreen", (void *) LXB_CSS_VALUE_LIGHTGREEN, 10, 0}, 
    {"plum", (void *) LXB_CSS_VALUE_PLUM, 4, 262}, 
    {"initial", (void *) LXB_CSS_VALUE_INITIAL, 7, 264}, 
    {"lightseagreen", (void *) LXB_CSS_VALUE_LIGHTSEAGREEN, 13, 0}, 
    {"mediumblue", (void *) LXB_CSS_VALUE_MEDIUMBLUE, 10, 93}, 
    {"activetext", (void *) LXB_CSS_VALUE_ACTIVETEXT, 10, 94}, 
    {"buttonface", (void *) LXB_CSS_VALUE_BUTTONFACE, 10, 96}, 
    {"each-line", (void *) LXB_CSS_VALUE_EACH_LINE, 9, 0}, 
    {"greenyellow", (void *) LXB_CSS_VALUE_GREENYELLOW, 11, 0}, 
    {"hanging", (void *) LXB_CSS_VALUE_HANGING, 7, 0}, 
    {"hotpink", (void *) LXB_CSS_VALUE_HOTPINK, 7, 0}, 
    {"midnightblue", (void *) LXB_CSS_VALUE_MIDNIGHTBLUE, 12, 0}, 
    {"stretch", (void *) LXB_CSS_VALUE_STRETCH, 7, 0}, 
    {"lime", (void *) LXB_CSS_VALUE_LIME, 4, 266}, 
    {"unset", (void *) LXB_CSS_VALUE_UNSET, 5, 267}, 
    {"x-small", (void *) LXB_CSS_VALUE_X_SMALL, 7, 0}, 
    {"upright", (void *) LXB_CSS_VALUE_UPRIGHT, 7, 0}, 
    {"xx-small", (void *) LXB_CSS_VALUE_XX_SMALL, 8, 108}, 
    {"lightblue", (void *) LXB_CSS_VALUE_LIGHTBLUE, 9, 270}, 
    {"aqua", (void *) LXB_CSS_VALUE_AQUA, 4, 271}, 
    {"mediumslateblue", (void *) LXB_CSS_VALUE_MEDIUMSLATEBLUE, 15, 110}, 
    {"lightskyblue", (void *) LXB_CSS_VALUE_LIGHTSKYBLUE, 12, 0}, 
    {"mediumturquoise", (void *) LXB_CSS_VALUE_MEDIUMTURQUOISE, 15, 113}, 
    {"plaintext", (void *) LXB_CSS_VALUE_PLAINTEXT, 9, 272}, 
    {"justify-all", (void *) LXB_CSS_VALUE_JUSTIFY_ALL, 11, 0}, 
    {"accentcolortext", (void *) LXB_CSS_VALUE_ACCENTCOLORTEXT, 15, 0}, 
    {"tan", (void *) LXB_CSS_VALUE_TAN, 3, 273}, 
    {"thin", (void *) LXB_CSS_VALUE_THIN, 4, 274}, 
    {"blueviolet", (void *) LXB_CSS_VALUE_BLUEVIOLET, 10, 275}, 
    {"run-in", (void *) LXB_CSS_VALUE_RUN_IN, 6, 276}, 
    {"match-parent", (void *) LXB_CSS_VALUE_MATCH_PARENT, 12, 0}, 
    {"mediumaquamarine", (void *) LXB_CSS_VALUE_MEDIUMAQUAMARINE, 16, 0}, 
    {"snow", (void *) LXB_CSS_VALUE_SNOW, 4, 280}, 
    {"small", (void *) LXB_CSS_VALUE_SMALL, 5, 0}, 
    {"sienna", (void *) LXB_CSS_VALUE_SIENNA, 6, 283}, 
    {"table-column", (void *) LXB_CSS_VALUE_TABLE_COLUMN, 12, 0}, 
    {"seashell", (void *) LXB_CSS_VALUE_SEASHELL, 8, 286}, 
    {"lightslategray", (void *) LXB_CSS_VALUE_LIGHTSLATEGRAY, 14, 287}, 
    {"ruby", (void *) LXB_CSS_VALUE_RUBY, 4, 0}, 
    {"sideways-rl", (void *) LXB_CSS_VALUE_SIDEWAYS_RL, 11, 0}, 
    {"all", (void *) LXB_CSS_VALUE_ALL, 3, 288}, 
    {"extra-condensed", (void *) LXB_CSS_VALUE_EXTRA_CONDENSED, 15, 0}, 
    {"indigo", (void *) LXB_CSS_VALUE_INDIGO, 6, 0}, 
    {"block-end", (void *) LXB_CSS_VALUE_BLOCK_END, 9, 134}, 
    {"bolder", (void *) LXB_CSS_VALUE_BOLDER, 6, 0}, 
    {"forestgreen", (void *) LXB_CSS_VALUE_FORESTGREEN, 11, 0}, 
    {"burlywood", (void *) LXB_CSS_VALUE_BURLYWOOD, 9, 0}, 
    {"blanchedalmond", (void *) LXB_CSS_VALUE_BLANCHEDALMOND, 14, 0}, 
    {"mediumvioletred", (void *) LXB_CSS_VALUE_MEDIUMVIOLETRED, 15, 0}, 
    {"papayawhip", (void *) LXB_CSS_VALUE_PAPAYAWHIP, 10, 0}, 
    {"buttonborder", (void *) LXB_CSS_VALUE_BUTTONBORDER, 12, 0}, 
    {"nowrap", (void *) LXB_CSS_VALUE_NOWRAP, 6, 0}, 
    {"double", (void *) LXB_CSS_VALUE_DOUBLE, 6, 141}, 
    {"smaller", (void *) LXB_CSS_VALUE_SMALLER, 7, 142}, 
    {"cornsilk", (void *) LXB_CSS_VALUE_CORNSILK, 8, 0}, 
    {"dodgerblue", (void *) LXB_CSS_VALUE_DODGERBLUE, 10, 144}, 
    {"sideways-lr", (void *) LXB_CSS_VALUE_SIDEWAYS_LR, 11, 0}, 
    {"deepskyblue", (void *) LXB_CSS_VALUE_DEEPSKYBLUE, 11, 0}, 
    {"skyblue", (void *) LXB_CSS_VALUE_SKYBLUE, 7, 0}, 
    {"gainsboro", (void *) LXB_CSS_VALUE_GAINSBORO, 9, 0}, 
    {"khaki", (void *) LXB_CSS_VALUE_KHAKI, 5, 290}, 
    {"firebrick", (void *) LXB_CSS_VALUE_FIREBRICK, 9, 153}, 
    {"snap-inline", (void *) LXB_CSS_VALUE_SNAP_INLINE, 11, 0}, 
    {"dotted", (void *) LXB_CSS_VALUE_DOTTED, 6, 293}, 
    {"flow", (void *) LXB_CSS_VALUE_FLOW, 4, 295}, 
    {"darkslateblue", (void *) LXB_CSS_VALUE_DARKSLATEBLUE, 13, 154}, 
    {"darkturquoise", (void *) LXB_CSS_VALUE_DARKTURQUOISE, 13, 0}, 
    {"hwb", (void *) LXB_CSS_VALUE_HWB, 3, 297}, 
    {"highlight", (void *) LXB_CSS_VALUE_HIGHLIGHT, 9, 0}, 
    {"palegoldenrod", (void *) LXB_CSS_VALUE_PALEGOLDENROD, 13, 159}, 
    {"visible", (void *) LXB_CSS_VALUE_VISIBLE, 7, 298}, 
    {"palevioletred", (void *) LXB_CSS_VALUE_PALEVIOLETRED, 13, 0}, 
    {"green", (void *) LXB_CSS_VALUE_GREEN, 5, 299}, 
    {"hidden", (void *) LXB_CSS_VALUE_HIDDEN, 6, 300}, 
    {"emoji", (void *) LXB_CSS_VALUE_EMOJI, 5, 301}, 
    {"darkgray", (void *) LXB_CSS_VALUE_DARKGRAY, 8, 303}, 
    {"tomato", (void *) LXB_CSS_VALUE_TOMATO, 6, 304}, 
    {"xx-large", (void *) LXB_CSS_VALUE_XX_LARGE, 8, 305}, 
    {"fangsong", (void *) LXB_CSS_VALUE_FANGSONG, 8, 306}, 
    {"start", (void *) LXB_CSS_VALUE_START, 5, 0}, 
    {"right", (void *) LXB_CSS_VALUE_RIGHT, 5, 307}, 
    {"revert", (void *) LXB_CSS_VALUE_REVERT, 6, 0}, 
    {"wavy", (void *) LXB_CSS_VALUE_WAVY, 4, 0}, 
    {"rgba", (void *) LXB_CSS_VALUE_RGBA, 4, 310}, 
    {"maroon", (void *) LXB_CSS_VALUE_MAROON, 6, 313}, 
    {"olive", (void *) LXB_CSS_VALUE_OLIVE, 5, 314}, 
    {"orange", (void *) LXB_CSS_VALUE_ORANGE, 6, 315}, 
    {"oldlace", (void *) LXB_CSS_VALUE_OLDLACE, 7, 317}, 
    {"overline", (void *) LXB_CSS_VALUE_OVERLINE, 8, 320}, 
    {"pre", (void *) LXB_CSS_VALUE_PRE, 3, 322}, 
    {"lch", (void *) LXB_CSS_VALUE_LCH, 3, 323}, 
    {"ruby-base", (void *) LXB_CSS_VALUE_RUBY_BASE, 9, 0}, 
    {"purple", (void *) LXB_CSS_VALUE_PURPLE, 6, 325}, 
    {"rtl", (void *) LXB_CSS_VALUE_RTL, 3, 328}, 
    {"bottom", (void *) LXB_CSS_VALUE_BOTTOM, 6, 329}, 
    {"flex", (void *) LXB_CSS_VALUE_FLEX, 4, 331}, 
    {"powderblue", (void *) LXB_CSS_VALUE_POWDERBLUE, 10, 0}, 
    {"ltr", (void *) LXB_CSS_VALUE_LTR, 3, 334}, 
    {"ultra-condensed", (void *) LXB_CSS_VALUE_ULTRA_CONDENSED, 15, 0}, 
    {"line-through", (void *) LXB_CSS_VALUE_LINE_THROUGH, 12, 336}, 
    {"sub", (void *) LXB_CSS_VALUE_SUB, 3, 337}, 
    {"lighter", (void *) LXB_CSS_VALUE_LIGHTER, 7, 340}, 
    {"lavender", (void *) LXB_CSS_VALUE_LAVENDER, 8, 341}, 
    {"inline-grid", (void *) LXB_CSS_VALUE_INLINE_GRID, 11, 0}, 
    {"row", (void *) LXB_CSS_VALUE_ROW, 3, 343}, 
    {"row-reverse", (void *) LXB_CSS_VALUE_ROW_REVERSE, 11, 0}, 
    {"rebeccapurple", (void *) LXB_CSS_VALUE_REBECCAPURPLE, 13, 0}, 
    {"content", (void *) LXB_CSS_VALUE_CONTENT, 7, 344}, 
    {"red", (void *) LXB_CSS_VALUE_RED, 3, 0}, 
    {"selecteditem", (void *) LXB_CSS_VALUE_SELECTEDITEM, 12, 0}, 
    {"oklch", (void *) LXB_CSS_VALUE_OKLCH, 5, 346}, 
    {"table", (void *) LXB_CSS_VALUE_TABLE, 5, 348}, 
    {"mark", (void *) LXB_CSS_VALUE_MARK, 4, 0}, 
    {"black", (void *) LXB_CSS_VALUE_BLACK, 5, 349}, 
    {"inline-block", (void *) LXB_CSS_VALUE_INLINE_BLOCK, 12, 0}, 
    {"clip", (void *) LXB_CSS_VALUE_CLIP, 4, 352}, 
    {"anywhere", (void *) LXB_CSS_VALUE_ANYWHERE, 8, 205}, 
    {"absolute", (void *) LXB_CSS_VALUE_ABSOLUTE, 8, 0}, 
    {"wheat", (void *) LXB_CSS_VALUE_WHEAT, 5, 0}, 
    {"underline", (void *) LXB_CSS_VALUE_UNDERLINE, 9, 353}, 
    {"top", (void *) LXB_CSS_VALUE_TOP, 3, 0}, 
    {"alphabetic", (void *) LXB_CSS_VALUE_ALPHABETIC, 10, 0}, 
    {"ui-monospace", (void *) LXB_CSS_VALUE_UI_MONOSPACE, 12, 0}, 
    {"darkkhaki", (void *) LXB_CSS_VALUE_DARKKHAKI, 9, 0}, 
    {"graytext", (void *) LXB_CSS_VALUE_GRAYTEXT, 8, 214}, 
    {"serif", (void *) LXB_CSS_VALUE_SERIF, 5, 354}, 
    {"list-item", (void *) LXB_CSS_VALUE_LIST_ITEM, 9, 0}, 
    {"coral", (void *) LXB_CSS_VALUE_CORAL, 5, 355}, 
    {"ellipsis", (void *) LXB_CSS_VALUE_ELLIPSIS, 8, 0}, 
    {"central", (void *) LXB_CSS_VALUE_CENTRAL, 7, 357}, 
    {"darkcyan", (void *) LXB_CSS_VALUE_DARKCYAN, 8, 358}, 
    {"hsla", (void *) LXB_CSS_VALUE_HSLA, 4, 359}, 
    {"darksalmon", (void *) LXB_CSS_VALUE_DARKSALMON, 10, 360}, 
    {"flow-root", (void *) LXB_CSS_VALUE_FLOW_ROOT, 9, 0}, 
    {"darkseagreen", (void *) LXB_CSS_VALUE_DARKSEAGREEN, 12, 0}, 
    {"table-header-group", (void *) LXB_CSS_VALUE_TABLE_HEADER_GROUP, 18, 361}, 
    {"darkolivegreen", (void *) LXB_CSS_VALUE_DARKOLIVEGREEN, 14, 0}, 
    {"gray", (void *) LXB_CSS_VALUE_GRAY, 4, 363}, 
    {"_angle", (void *) LXB_CSS_VALUE__ANGLE, 6, 0}, 
    {"ghostwhite", (void *) LXB_CSS_VALUE_GHOSTWHITE, 10, 229}, 
    {"thick", (void *) LXB_CSS_VALUE_THICK, 5, 0}, 
    {"wrap-reverse", (void *) LXB_CSS_VALUE_WRAP_REVERSE, 12, 0}, 
    {"math", (void *) LXB_CSS_VALUE_MATH, 4, 365}, 
    {"_length", (void *) LXB_CSS_VALUE__LENGTH, 7, 366}, 
    {"fuchsia", (void *) LXB_CSS_VALUE_FUCHSIA, 7, 0}, 
    {"wrap", (void *) LXB_CSS_VALUE_WRAP, 4, 367}, 
    {"fixed", (void *) LXB_CSS_VALUE_FIXED, 5, 235}, 
    {"lightyellow", (void *) LXB_CSS_VALUE_LIGHTYELLOW, 11, 0}, 
    {"clear", (void *) LXB_CSS_VALUE_CLEAR, 5, 237}, 
    {"deeppink", (void *) LXB_CSS_VALUE_DEEPPINK, 8, 0}, 
    {"last", (void *) LXB_CSS_VALUE_LAST, 4, 368}, 
    {"full-size-kana", (void *) LXB_CSS_VALUE_FULL_SIZE_KANA, 14, 0}, 
    {"flex-end", (void *) LXB_CSS_VALUE_FLEX_END, 8, 0}, 
    {"palegreen", (void *) LXB_CSS_VALUE_PALEGREEN, 9, 370}, 
    {"linktext", (void *) LXB_CSS_VALUE_LINKTEXT, 8, 0}, 
    {"text-bottom", (void *) LXB_CSS_VALUE_TEXT_BOTTOM, 11, 245}, 
    {"inset", (void *) LXB_CSS_VALUE_INSET, 5, 0}, 
    {"inline-flex", (void *) LXB_CSS_VALUE_INLINE_FLEX, 11, 0}, 
    {"inherit", (void *) LXB_CSS_VALUE_INHERIT, 7, 0}, 
    {"navy", (void *) LXB_CSS_VALUE_NAVY, 4, 0}, 
    {"grid", (void *) LXB_CSS_VALUE_GRID, 4, 252}, 
    {"ruby-base-container", (void *) LXB_CSS_VALUE_RUBY_BASE_CONTAINER, 19, 371}, 
    {"orchid", (void *) LXB_CSS_VALUE_ORCHID, 6, 0}, 
    {"inline-start", (void *) LXB_CSS_VALUE_INLINE_START, 12, 0}, 
    {"border-box", (void *) LXB_CSS_VALUE_BORDER_BOX, 10, 0}, 
    {"peru", (void *) LXB_CSS_VALUE_PERU, 4, 372}, 
    {"currentcolor", (void *) LXB_CSS_VALUE_CURRENTCOLOR, 12, 255}, 
    {"lightgoldenrodyellow", (void *) LXB_CSS_VALUE_LIGHTGOLDENRODYELLOW, 20, 0}, 
    {"space-around", (void *) LXB_CSS_VALUE_SPACE_AROUND, 12, 0}, 
    {"semi-expanded", (void *) LXB_CSS_VALUE_SEMI_EXPANDED, 13, 0}, 
    {"semi-condensed", (void *) LXB_CSS_VALUE_SEMI_CONDENSED, 14, 0}, 
    {"inline-table", (void *) LXB_CSS_VALUE_INLINE_TABLE, 12, 0}, 
    {"lightcyan", (void *) LXB_CSS_VALUE_LIGHTCYAN, 9, 261}, 
    {"limegreen", (void *) LXB_CSS_VALUE_LIMEGREEN, 9, 0}, 
    {"lightsalmon", (void *) LXB_CSS_VALUE_LIGHTSALMON, 11, 263}, 
    {"isolate-override", (void *) LXB_CSS_VALUE_ISOLATE_OVERRIDE, 16, 0}, 
    {"keep-all", (void *) LXB_CSS_VALUE_KEEP_ALL, 8, 265}, 
    {"lemonchiffon", (void *) LXB_CSS_VALUE_LEMONCHIFFON, 12, 0}, 
    {"sideways", (void *) LXB_CSS_VALUE_SIDEWAYS, 8, 0}, 
    {"large", (void *) LXB_CSS_VALUE_LARGE, 5, 268}, 
    {"loose", (void *) LXB_CSS_VALUE_LOOSE, 5, 269}, 
    {"honeydew", (void *) LXB_CSS_VALUE_HONEYDEW, 8, 0}, 
    {"lowercase", (void *) LXB_CSS_VALUE_LOWERCASE, 9, 0}, 
    {"floralwhite", (void *) LXB_CSS_VALUE_FLORALWHITE, 11, 0}, 
    {"lightsteelblue", (void *) LXB_CSS_VALUE_LIGHTSTEELBLUE, 14, 0}, 
    {"marktext", (void *) LXB_CSS_VALUE_MARKTEXT, 8, 0}, 
    {"none", (void *) LXB_CSS_VALUE_NONE, 4, 0}, 
    {"buttontext", (void *) LXB_CSS_VALUE_BUTTONTEXT, 10, 0}, 
    {"region", (void *) LXB_CSS_VALUE_REGION, 6, 277}, 
    {"block-start", (void *) LXB_CSS_VALUE_BLOCK_START, 11, 278}, 
    {"min-content", (void *) LXB_CSS_VALUE_MIN_CONTENT, 11, 279}, 
    {"max-content", (void *) LXB_CSS_VALUE_MAX_CONTENT, 11, 0}, 
    {"lightgray", (void *) LXB_CSS_VALUE_LIGHTGRAY, 9, 281}, 
    {"lightgrey", (void *) LXB_CSS_VALUE_LIGHTGREY, 9, 282}, 
    {"rosybrown", (void *) LXB_CSS_VALUE_ROSYBROWN, 9, 0}, 
    {"scroll", (void *) LXB_CSS_VALUE_SCROLL, 6, 284}, 
    {"digits", (void *) LXB_CSS_VALUE_DIGITS, 6, 285}, 
    {"navajowhite", (void *) LXB_CSS_VALUE_NAVAJOWHITE, 11, 0}, 
    {"table-caption", (void *) LXB_CSS_VALUE_TABLE_CAPTION, 13, 0}, 
    {"lightslategrey", (void *) LXB_CSS_VALUE_LIGHTSLATEGREY, 14, 0}, 
    {"yellow", (void *) LXB_CSS_VALUE_YELLOW, 6, 289}, 
    {"break-spaces", (void *) LXB_CSS_VALUE_BREAK_SPACES, 12, 0}, 
    {"oklab", (void *) LXB_CSS_VALUE_OKLAB, 5, 291}, 
    {"slateblue", (void *) LXB_CSS_VALUE_SLATEBLUE, 9, 292}, 
    {"steelblue", (void *) LXB_CSS_VALUE_STEELBLUE, 9, 0}, 
    {"dashed", (void *) LXB_CSS_VALUE_DASHED, 6, 294}, 
    {"transparent", (void *) LXB_CSS_VALUE_TRANSPARENT, 11, 0}, 
    {"darkred", (void *) LXB_CSS_VALUE_DARKRED, 7, 296}, 
    {"olivedrab", (void *) LXB_CSS_VALUE_OLIVEDRAB, 9, 0}, 
    {"darkorchid", (void *) LXB_CSS_VALUE_DARKORCHID, 10, 0}, 
    {"darkgoldenrod", (void *) LXB_CSS_VALUE_DARKGOLDENROD, 13, 0}, 
    {"_number", (void *) LXB_CSS_VALUE__NUMBER, 7, 0}, 
    {"_integer", (void *) LXB_CSS_VALUE__INTEGER, 8, 0}, 
    {"dimgray", (void *) LXB_CSS_VALUE_DIMGRAY, 7, 302}, 
    {"dimgrey", (void *) LXB_CSS_VALUE_DIMGREY, 7, 0}, 
    {"darkgrey", (void *) LXB_CSS_VALUE_DARKGREY, 8, 0}, 
    {"x-large", (void *) LXB_CSS_VALUE_X_LARGE, 7, 0}, 
    {"horizontal-tb", (void *) LXB_CSS_VALUE_HORIZONTAL_TB, 13, 0}, 
    {"xxx-large", (void *) LXB_CSS_VALUE_XXX_LARGE, 9, 0}, 
    {"strict", (void *) LXB_CSS_VALUE_STRICT, 6, 308}, 
    {"darkslategray", (void *) LXB_CSS_VALUE_DARKSLATEGRAY, 13, 309}, 
    {"darkslategrey", (void *) LXB_CSS_VALUE_DARKSLATEGREY, 13, 0}, 
    {"brown", (void *) LXB_CSS_VALUE_BROWN, 5, 311}, 
    {"system-ui", (void *) LXB_CSS_VALUE_SYSTEM_UI, 9, 312}, 
    {"accentcolor", (void *) LXB_CSS_VALUE_ACCENTCOLOR, 11, 0}, 
    {"ruby-text", (void *) LXB_CSS_VALUE_RUBY_TEXT, 9, 0}, 
    {"cursive", (void *) LXB_CSS_VALUE_CURSIVE, 7, 0}, 
    {"moccasin", (void *) LXB_CSS_VALUE_MOCCASIN, 8, 316}, 
    {"collapse", (void *) LXB_CSS_VALUE_COLLAPSE, 8, 0}, 
    {"oblique", (void *) LXB_CSS_VALUE_OBLIQUE, 7, 318}, 
    {"cadetblue", (void *) LXB_CSS_VALUE_CADETBLUE, 9, 319}, 
    {"chocolate", (void *) LXB_CSS_VALUE_CHOCOLATE, 9, 0}, 
    {"chartreuse", (void *) LXB_CSS_VALUE_CHARTREUSE, 10, 321}, 
    {"capitalize", (void *) LXB_CSS_VALUE_CAPITALIZE, 10, 0}, 
    {"yellowgreen", (void *) LXB_CSS_VALUE_YELLOWGREEN, 11, 0}, 
    {"page", (void *) LXB_CSS_VALUE_PAGE, 4, 324}, 
    {"selecteditemtext", (void *) LXB_CSS_VALUE_SELECTEDITEMTEXT, 16, 0}, 
    {"cornflowerblue", (void *) LXB_CSS_VALUE_CORNFLOWERBLUE, 14, 326}, 
    {"mediumseagreen", (void *) LXB_CSS_VALUE_MEDIUMSEAGREEN, 14, 327}, 
    {"column-reverse", (void *) LXB_CSS_VALUE_COLUMN_REVERSE, 14, 0}, 
    {"ui-rounded", (void *) LXB_CSS_VALUE_UI_ROUNDED, 10, 0}, 
    {"medium", (void *) LXB_CSS_VALUE_MEDIUM, 6, 330}, 
    {"pre-line", (void *) LXB_CSS_VALUE_PRE_LINE, 8, 0}, 
    {"minimum", (void *) LXB_CSS_VALUE_MINIMUM, 7, 332}, 
    {"maximum", (void *) LXB_CSS_VALUE_MAXIMUM, 7, 333}, 
    {"mediumspringgreen", (void *) LXB_CSS_VALUE_MEDIUMSPRINGGREEN, 17, 0}, 
    {"mintcream", (void *) LXB_CSS_VALUE_MINTCREAM, 9, 335}, 
    {"ultra-expanded", (void *) LXB_CSS_VALUE_ULTRA_EXPANDED, 14, 0}, 
    {"paleturquoise", (void *) LXB_CSS_VALUE_PALETURQUOISE, 13, 0}, 
    {"larger", (void *) LXB_CSS_VALUE_LARGER, 6, 338}, 
    {"content-box", (void *) LXB_CSS_VALUE_CONTENT_BOX, 11, 339}, 
    {"lavenderblush", (void *) LXB_CSS_VALUE_LAVENDERBLUSH, 13, 0}, 
    {"indianred", (void *) LXB_CSS_VALUE_INDIANRED, 9, 0}, 
    {"inline-end", (void *) LXB_CSS_VALUE_INLINE_END, 10, 342}, 
    {"inter-word", (void *) LXB_CSS_VALUE_INTER_WORD, 10, 0}, 
    {"manual", (void *) LXB_CSS_VALUE_MANUAL, 6, 0}, 
    {"justify", (void *) LXB_CSS_VALUE_JUSTIFY, 7, 345}, 
    {"break-all", (void *) LXB_CSS_VALUE_BREAK_ALL, 9, 0}, 
    {"canvastext", (void *) LXB_CSS_VALUE_CANVASTEXT, 10, 347}, 
    {"mathematical", (void *) LXB_CSS_VALUE_MATHEMATICAL, 12, 0}, 
    {"full-width", (void *) LXB_CSS_VALUE_FULL_WIDTH, 10, 0}, 
    {"block", (void *) LXB_CSS_VALUE_BLOCK, 5, 350}, 
    {"blink", (void *) LXB_CSS_VALUE_BLINK, 5, 351}, 
    {"thistle", (void *) LXB_CSS_VALUE_THISTLE, 7, 0}, 
    {"turquoise", (void *) LXB_CSS_VALUE_TURQUOISE, 9, 0}, 
    {"uppercase", (void *) LXB_CSS_VALUE_UPPERCASE, 9, 0}, 
    {"text-top", (void *) LXB_CSS_VALUE_TEXT_TOP, 8, 0}, 
    {"ivory", (void *) LXB_CSS_VALUE_IVORY, 5, 356}, 
    {"inter-character", (void *) LXB_CSS_VALUE_INTER_CHARACTER, 15, 0}, 
    {"fantasy", (void *) LXB_CSS_VALUE_FANTASY, 7, 0}, 
    {"sans-serif", (void *) LXB_CSS_VALUE_SANS_SERIF, 10, 0}, 
    {"darkgreen", (void *) LXB_CSS_VALUE_DARKGREEN, 9, 0}, 
    {"table-row-group", (void *) LXB_CSS_VALUE_TABLE_ROW_GROUP, 15, 0}, 
    {"table-footer-group", (void *) LXB_CSS_VALUE_TABLE_FOOTER_GROUP, 18, 362}, 
    {"table-column-group", (void *) LXB_CSS_VALUE_TABLE_COLUMN_GROUP, 18, 0}, 
    {"grey", (void *) LXB_CSS_VALUE_GREY, 4, 364}, 
    {"vertical-rl", (void *) LXB_CSS_VALUE_VERTICAL_RL, 11, 0}, 
    {"both", (void *) LXB_CSS_VALUE_BOTH, 4, 0}, 
    {"_percentage", (void *) LXB_CSS_VALUE__PERCENTAGE, 11, 0}, 
    {"ui-serif", (void *) LXB_CSS_VALUE_UI_SERIF, 8, 0}, 
    {"left", (void *) LXB_CSS_VALUE_LEFT, 4, 369}, 
    {"ui-sans-serif", (void *) LXB_CSS_VALUE_UI_SANS_SERIF, 13, 0}, 
    {"condensed", (void *) LXB_CSS_VALUE_CONDENSED, 9, 0}, 
    {"ruby-text-container", (void *) LXB_CSS_VALUE_RUBY_TEXT_CONTAINER, 19, 0}, 
    {"orangered", (void *) LXB_CSS_VALUE_ORANGERED, 9, 0}
};


#endif /* LXB_CSS_VALUE_RES_H */
