/*
 * Copyright (C) %%YEAR%% Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/style/property_compute.py"!
 * Do not change this file!
 */


#ifndef LXB_STYLE_PROPERTY_COMPUTE_RES_H
#define LXB_STYLE_PROPERTY_COMPUTE_RES_H


static const lxb_style_property_compute_f
lxb_style_property_compute_data[LXB_CSS_PROPERTY__LAST_ENTRY] =
{
%%BODY%%
};


#endif /* LXB_STYLE_PROPERTY_COMPUTE_RES_H */
