/*
 * Copyright (C) 2026 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/css/names.py"!
 * Do not change this file!
 */


#ifndef LXB_CSS_AT_RULE_RES_H
#define LXB_CSS_AT_RULE_RES_H

#include "lexbor/core/shs.h"
#include "lexbor/css/at_rule/const.h"


static const lxb_css_entry_at_rule_data_t lxb_css_at_rule_data[LXB_CSS_AT_RULE__LAST_ENTRY] = 
{
    {
        .name = (lxb_char_t *) "#undef",
        .length = 6,
        .unique = LXB_CSS_AT_RULE__UNDEF,
        .cbs = &lxb_css_at_rule__undef_cb,
        .create = lxb_css_at_rule__undef_create,
        .destroy = lxb_css_at_rule__undef_destroy,
        .serialize = lxb_css_at_rule__undef_serialize,
        .initial = (void *) (uintptr_t) LXB_CSS_AT_RULE__UNDEF
    },
    {
        .name = (lxb_char_t *) "#сustom",
        .length = 7,
        .unique = LXB_CSS_AT_RULE__CUSTOM,
        .cbs = &lxb_css_at_rule__custom_cb,
        .create = lxb_css_at_rule__custom_create,
        .destroy = lxb_css_at_rule__custom_destroy,
        .serialize = lxb_css_at_rule__custom_serialize,
        .initial = (void *) (uintptr_t) LXB_CSS_AT_RULE__CUSTOM
    },
    {
        .name = (lxb_char_t *) "font-face",
        .length = 9,
        .unique = LXB_CSS_AT_RULE_FONT_FACE,
        .cbs = &lxb_css_at_rule_font_face_cb,
        .create = lxb_css_at_rule_font_face_create,
        .destroy = lxb_css_at_rule_font_face_destroy,
        .serialize = lxb_css_at_rule_font_face_serialize,
        .initial = NULL
    },
    {
        .name = (lxb_char_t *) "media",
        .length = 5,
        .unique = LXB_CSS_AT_RULE_MEDIA,
        .cbs = &lxb_css_at_rule_media_cb,
        .create = lxb_css_at_rule_media_create,
        .destroy = lxb_css_at_rule_media_destroy,
        .serialize = lxb_css_at_rule_media_serialize,
        .initial = NULL
    },
    {
        .name = (lxb_char_t *) "namespace",
        .length = 9,
        .unique = LXB_CSS_AT_RULE_NAMESPACE,
        .cbs = &lxb_css_at_rule_namespace_cb,
        .create = lxb_css_at_rule_namespace_create,
        .destroy = lxb_css_at_rule_namespace_destroy,
        .serialize = lxb_css_at_rule_namespace_serialize,
        .initial = NULL
    }
};

static const lexbor_shs_entry_t lxb_css_at_rule_shs[6] = 
{
    {NULL, NULL, 5, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"media", (void *) &lxb_css_at_rule_data[LXB_CSS_AT_RULE_MEDIA], 5, 0}, 
    {"font-face", (void *) &lxb_css_at_rule_data[LXB_CSS_AT_RULE_FONT_FACE], 9, 0}, 
    {"namespace", (void *) &lxb_css_at_rule_data[LXB_CSS_AT_RULE_NAMESPACE], 9, 0}
};


#endif /* LXB_CSS_AT_RULE_RES_H */
